import type { CmsDocumentKind } from "@workspace/api-zod";

export type CmsFieldConsumer = "public-and-preview" | "public" | "preview-only" | "schema-only" | "derived";

export type CmsFieldCoverage = {
  path: string;
  editor: string;
  draft: "editable" | "derived" | "read-only";
  publish: "required" | "optional" | "not-applicable";
  consumer: CmsFieldConsumer;
  note?: string;
};

const editable = (path: string, editor: string, publish: CmsFieldCoverage["publish"], consumer: CmsFieldConsumer = "public-and-preview", note?: string): CmsFieldCoverage => ({
  path, editor, draft: "editable", publish, consumer, note,
});
const derived = (path: string, editor: string, consumer: CmsFieldConsumer = "derived", note?: string): CmsFieldCoverage => ({
  path, editor, draft: "derived", publish: "not-applicable", consumer, note,
});
const readOnly = (path: string, editor: string, consumer: CmsFieldConsumer, note: string): CmsFieldCoverage => ({
  path, editor, draft: "read-only", publish: "optional", consumer, note,
});

/**
 * Editorial field inventory for all ten governed document kinds.
 *
 * This deliberately records fields whose public consumer is not confirmed
 * instead of inventing controls or deleting their stored values. The registry
 * is UI-facing evidence; the runtime Zod contract remains authoritative.
 */
export const CMS_FIELD_COVERAGE: Record<CmsDocumentKind, readonly CmsFieldCoverage[]> = {
  person: [
    derived("schemaVersion", "runtime contract", "derived"),
    editable("role", "ContentEditor → Role", "required"),
    editable("title", "ContentEditor → Public title", "required"),
    editable("biography", "ContentEditor → Biography", "optional"),
    editable("contribution", "ContentEditor → Contribution", "optional"),
    editable("focusAreas[]", "ContentEditor → Focus areas", "optional"),
    editable("profileLinks[]", "ContentEditor → Profile links", "optional"),
    editable("identityMedia", "ContentEditor → Identity image", "optional"),
    readOnly("identityMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved; new selections use a versioned media reference."),
    editable("approvedFallback", "ContentEditor → Approved fallback", "optional"),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only", "No confirmed public consumer; selected UUIDs are retained and removable explicitly."),
  ],
  partner: [
    derived("schemaVersion", "runtime contract"),
    editable("allianceCategory", "ContentEditor → Alliance category", "required"),
    editable("positioning", "ContentEditor → Positioning", "required"),
    editable("facts[]", "ContentEditor → Facts", "optional"),
    editable("evidence[]", "ContentEditor → Evidence", "optional"),
    editable("coverage[]", "ContentEditor → Coverage", "optional"),
    editable("contribution", "ContentEditor → Contribution", "optional"),
    editable("website", "ContentEditor → Website", "optional"),
    editable("logoMedia", "ContentEditor → Partner logo", "optional"),
    readOnly("logoMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("relationshipStatus", "ContentEditor → Relationship status", "required"),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  platform: [
    derived("schemaVersion", "runtime contract"),
    editable("category", "ContentEditor → Category", "required"),
    editable("summary", "ContentEditor → Summary", "required"),
    editable("heroMedia", "ContentEditor → Hero image", "optional"),
    readOnly("heroMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("template", "ContentEditor → Template", "required"),
    editable("sections[]", "ContentEditor → Structured page sections", "optional"),
    editable("capabilities[]", "ContentEditor → Capabilities", "optional"),
    editable("differentiators[]", "ContentEditor → Differentiators", "optional"),
    editable("cta", "ContentEditor → Safe destination", "optional"),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  publication: [
    derived("schemaVersion", "runtime contract"),
    editable("variant", "ContentEditor → Publication variant", "required"),
    editable("teaser", "ContentEditor → Teaser", "required"),
    editable("body[]", "ContentEditor → Structured body", "required"),
    editable("author", "ContentEditor → Author", "required"),
    editable("publicationDate", "ContentEditor → Publication date", "required"),
    editable("updatedDate", "ContentEditor → Updated date", "optional"),
    editable("readingTimeMinutes", "ContentEditor → Reading time", "optional"),
    editable("topics[]", "ContentEditor → Topics", "optional"),
    editable("sectors[]", "ContentEditor → Sectors", "optional"),
    editable("platformIds[]", "ContentEditor → Platform record picker", "optional", "schema-only", "Stored relationship has no confirmed public consumer; preserve it without a raw UUID editor."),
    editable("heroMedia", "ContentEditor → Hero image", "optional"),
    readOnly("heroMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("pdfMedia", "ContentEditor → POV PDF", "optional"),
    readOnly("pdfMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    readOnly("social.title", "advanced structured view", "schema-only", "No confirmed public consumer; preserve stored social copy until its consumer is defined."),
    readOnly("social.description", "advanced structured view", "schema-only", "No confirmed public consumer; preserve stored social copy until its consumer is defined."),
    editable("social.imageMedia", "ContentEditor → Social sharing image", "optional"),
    readOnly("social.imageMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  "case-study": [
    derived("schemaVersion", "runtime contract"),
    editable("variant", "ContentEditor → Case variant", "required"),
    editable("disclosure", "ContentEditor → Disclosure", "required"),
    editable("sector", "ContentEditor → Approved sector multi-select", "required"),
    editable("organizationDescriptor", "ContentEditor → Organization descriptor", "required"),
    editable("engagementType", "ContentEditor → Engagement type", "required"),
    editable("deliveryStage", "ContentEditor → Delivery stage", "required"),
    editable("impactClassification", "ContentEditor → Impact classification", "required"),
    editable("impactStatement", "ContentEditor → Public capability statement", "required"),
    editable("disclosureNote", "ContentEditor → Disclosure note", "required"),
    editable("publicEvidenceStatus", "ContentEditor → Evidence approval", "required"),
    editable("relatedIndustries[]", "ContentEditor → Approved industry multi-select", "optional"),
    editable("visual", "ContentEditor → Reconstruction fields", "required"),
    editable("mandate", "ContentEditor → Mandate", "required"),
    editable("context", "ContentEditor → Context", "optional"),
    editable("constraints[]", "ContentEditor → Constraints", "optional"),
    editable("work[]", "ContentEditor → Structured work", "optional"),
    editable("controls[]", "ContentEditor → Controls", "optional"),
    editable("outcomes[]", "ContentEditor → Outcomes", "optional"),
    editable("evidence[]", "ContentEditor → Evidence", "optional"),
    editable("quote", "ContentEditor → Quote and attribution", "optional"),
    editable("heroMedia", "ContentEditor → Case-study hero image", "optional"),
    readOnly("heroMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("cta", "ContentEditor → Safe destination", "optional"),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  industry: [
    derived("schemaVersion", "runtime contract"),
    editable("legacyPath", "IndustryVisualWorkspace → Hero", "required"),
    editable("name", "IndustryVisualWorkspace → Hero", "required"),
    editable("shortName", "IndustryVisualWorkspace → Hero", "required"),
    editable("thesis", "IndustryVisualWorkspace → Hero", "required"),
    editable("accent", "IndustryVisualWorkspace → Hero", "required"),
    editable("dek", "IndustryVisualWorkspace → Hero", "required"),
    editable("opportunity", "IndustryVisualWorkspace → Opportunity", "required"),
    editable("capabilities[]", "IndustryVisualWorkspace → Capabilities", "required"),
    editable("selectedWork", "IndustryVisualWorkspace → Selected work", "required"),
    editable("image", "IndustryVisualWorkspace → Legacy image", "required"),
    editable("imageAlt", "IndustryVisualWorkspace → Hero image", "required"),
    editable("variant", "IndustryVisualWorkspace → Variant", "required"),
    editable("pressures[]", "IndustryVisualWorkspace → Pressures", "required"),
    editable("reversal", "IndustryVisualWorkspace → Reversal", "required"),
    editable("myth", "IndustryVisualWorkspace → Myth", "required"),
    editable("gcc", "IndustryVisualWorkspace → GCC context", "required"),
    editable("service", "IndustryVisualWorkspace → Service destination", "required"),
    editable("uses[]", "IndustryVisualWorkspace → Evidence uses", "required"),
    editable("sources[]", "IndustryVisualWorkspace → Source trail", "required", "preview-only"),
    editable("educationPov", "ContentEditor → Education specialist fields", "optional"),
    editable("bankingPov", "ContentEditor → Banking specialist fields", "optional"),
    editable("publicSectorPov", "ContentEditor → Public Sector specialist fields", "optional"),
    editable("heroMedia", "IndustryVisualWorkspace → Hero media", "optional"),
    readOnly("heroMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("supportingMedia[]", "IndustryVisualWorkspace → Supporting media", "optional"),
    editable("verificationDate", "IndustryVisualWorkspace → Governance", "required", "preview-only"),
    editable("reviewDate", "IndustryVisualWorkspace → Governance", "required", "preview-only"),
    editable("visibility", "IndustryVisualWorkspace → Governance", "required"),
    editable("order", "IndustryVisualWorkspace → Governance", "optional"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  framework: [
    derived("schemaVersion", "runtime contract"),
    editable("template", "ContentEditor → Framework template", "required"),
    editable("hero", "ContentEditor → Methodology editorial composition", "required"),
    editable("hero.breadcrumb", "ContentEditor → Methodology editorial composition", "required"),
    editable("hero.title", "ContentEditor → Methodology editorial composition", "required"),
    editable("hero.description", "ContentEditor → Methodology editorial composition", "required"),
    editable("hero.supportingText", "ContentEditor → Methodology editorial composition", "optional"),
    editable("hero.media", "ContentEditor → Methodology editorial composition", "required"),
    editable("hero.imageCaptionSubtitle", "ContentEditor → Methodology editorial composition", "optional"),
    editable("hero.imageCaptionTitle", "ContentEditor → Methodology editorial composition", "optional"),
    editable("editorial", "ContentEditor → fixed template editorial slots", "required"),
    derived("canonical", "fixed methodology and assessment identifiers"),
    editable("teaser", "ContentEditor → Teaser", "required"),
    editable("handoverExplanation", "ContentEditor → Handover explanation", "required"),
    editable("methodology[]", "ContentEditor → Structured methodology", "required"),
    editable("workedExample", "ContentEditor → Worked example", "required"),
    editable("sectorExamples[]", "ContentEditor → Sector examples", "optional"),
    editable("guardrails", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.heading", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.opening", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.definition", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.bankExample", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.comparisonHeading", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.comparisonColumns", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.comparisonRows[]", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.unit", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.firstFigure.altText", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.firstFigure.captionLabel", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.firstFigure.captionLead", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.firstFigure.captionBody", "ContentEditor → Guardrails and authority subsection", "optional"),
    derived("guardrails.firstFigure.asset", "fixed local diagram identifier"),
    editable("guardrails.summary", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.lead", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.handover", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.rules[]", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.caveat", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.disclosureLabel", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.firstFigure.altText", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.firstFigure.captionLabel", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.firstFigure.captionLead", "ContentEditor → Summary-first narrative", "optional"),
    editable("guardrails.summary.firstFigure.captionBody", "ContentEditor → Summary-first narrative", "optional"),
    derived("guardrails.summary.firstFigure.asset", "fixed local diagram identifier"),
    editable("guardrails.interaction", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.secondFigure.altText", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.secondFigure.captionLabel", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.secondFigure.captionLead", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("guardrails.secondFigure.captionBody", "ContentEditor → Guardrails and authority subsection", "optional"),
    derived("guardrails.secondFigure.asset", "fixed local diagram identifier"),
    editable("guardrails.designRule", "ContentEditor → Guardrails and authority subsection", "optional"),
    editable("heroMedia", "ContentEditor → Framework hero image", "required"),
    readOnly("heroMediaId", "legacy immutable media compatibility", "preview-only", "Deprecated legacy media id is preserved."),
    editable("cta", "ContentEditor → Safe destination", "optional"),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  office: [
    derived("schemaVersion", "runtime contract"),
    editable("city", "ContentEditor → City", "required"),
    editable("address", "ContentEditor → Full postal address", "required"),
    editable("phone", "ContentEditor → Phone number", "optional"),
    editable("visibility", "ContentEditor → Governance", "required"),
    editable("order", "ContentEditor → Governance", "optional"),
    editable("sources[]", "ContentEditor → Sources", "not-applicable", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "not-applicable", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "not-applicable", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
  "site-configuration": [
    derived("schemaVersion", "runtime contract"),
    editable("configuration", "ContactSettings / ContentEditor", "required", "public"),
    editable("contactEmail", "ContactSettings / ContentEditor", "required", "public"),
    editable("page", "ContentEditor → Hero film assignment", "required", "public"),
    editable("hero.posterMediaId", "ContentEditor → Poster media", "required", "public"),
    editable("hero.posterMediaVersionId", "ContentEditor → Poster media version", "required", "public"),
    editable("hero.sources[]", "ContentEditor → MP4/WebM sources", "required", "public"),
  ],
  "landing-page": [
    derived("schemaVersion", "runtime contract"),
    editable("pagePath", "ContentEditor → Public page path", "required", "public"),
    editable("template", "ContentEditor → Governed template", "required", "public"),
    editable("narrative", "ContentEditor → Opening narrative", "required", "public"),
    editable("sections[]", "ContentEditor → Governed page sections", "required", "public"),
    editable("cta", "ContentEditor → Safe destination", "optional", "public"),
    editable("seo", "DocumentDetail → SEO controls", "optional", "public-and-preview"),
    editable("legal", "ContentEditor → Legal disclaimer", "optional", "public"),
    editable("visualReferences[]", "ContentEditor → Governed visual references", "optional", "public"),
    editable("visibility", "ContentEditor → Governance", "required", "public"),
    editable("order", "ContentEditor → Governance", "optional", "public"),
    editable("sources[]", "ContentEditor → Sources", "required", "preview-only"),
    editable("verificationDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("reviewDate", "ContentEditor → Governance", "required", "preview-only"),
    editable("relatedIds[]", "ContentEditor → Related record picker", "optional", "schema-only"),
  ],
};

export const CMS_FIELD_COVERAGE_KINDS = Object.freeze(Object.keys(CMS_FIELD_COVERAGE) as CmsDocumentKind[]);

export function fieldCoverageFor(kind: CmsDocumentKind) {
  return CMS_FIELD_COVERAGE[kind];
}
