import { ArrowDownRight, ArrowRight, Menu, MoveUpRight, Play, X } from "lucide-react";
import { useState } from "react";

const gradient = "linear-gradient(105deg,#7547d8 0%,#dc4cb4 48%,#ff6e5b 100%)";

function ArrowButton({ children, dark = false }: { children: string; dark?: boolean }) {
  return <button className={`as-button ${dark ? "dark" : ""}`}>{children}<ArrowRight size={17} strokeWidth={2.2} /></button>;
}

export function AgenticSurge() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeForce, setActiveForce] = useState("Agents");

  return (
    <main className="agentic-surge">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&family=Syne:wght@600;700;800&display=swap');
        .agentic-surge{--ink:#102b56;--soft:#f6f4f0;--line:#d4dce5;--pink:#d84db1;color:var(--ink);font-family:Manrope,sans-serif;background:#fff;overflow:hidden}
        .agentic-surge *{box-sizing:border-box}.agentic-surge button{font:inherit}.agentic-surge a{text-decoration:none;color:inherit}
        .as-nav{height:88px;display:flex;align-items:center;justify-content:space-between;padding:18px 4.8vw;border-bottom:1px solid #e5e9ed;position:relative;z-index:20;background:rgba(255,255,255,.94)}
        .as-logo{width:146px;height:50px;object-fit:contain;object-position:left center;transform:scale(1.65);transform-origin:left center}.as-navlinks{display:flex;gap:26px;align-items:center;font-size:13px;font-weight:700}.as-navlinks a{cursor:pointer}.as-navlinks a:hover{color:#c149ab}.as-nav .as-button{padding:12px 17px;font-size:12px}.as-menu{display:none;border:0;background:none;color:var(--ink)}
        .as-button{border:0;background:${gradient};color:white;padding:16px 21px;display:inline-flex;align-items:center;gap:14px;font-weight:800;font-size:13px;cursor:pointer;transition:transform .2s ease,box-shadow .2s ease}.as-button:hover{transform:translate(4px,-3px);box-shadow:-5px 6px 0 var(--ink)}.as-button.dark{background:var(--ink);box-shadow:none}.as-button.dark:hover{box-shadow:-5px 6px 0 #f66872}
        .as-hero{min-height:690px;position:relative;padding:52px 4.8vw 66px;display:grid;grid-template-columns:1.06fr .94fr;align-items:end;isolation:isolate;background:linear-gradient(180deg,#fff 0%,#fbf8fb 100%)}.as-eyebrow,.as-index,.as-kicker{font-family:"DM Mono",monospace;text-transform:uppercase;font-size:11px;letter-spacing:.08em}.as-eyebrow{grid-column:1;color:#c548a7;font-weight:500;margin-bottom:40px}.as-hero-copy{grid-column:1;position:relative;z-index:3}.as-hero h1{font-family:Syne,sans-serif;font-size:clamp(52px,6.5vw,108px);letter-spacing:-.08em;line-height:.91;margin:0;max-width:840px;font-weight:800}.as-hero h1 .shift{display:block;margin-left:15%;color:#f06077}.as-hero h1 .deep{color:var(--ink)}.as-intro{font-size:17px;line-height:1.55;max-width:490px;margin:31px 0;color:#31476a}.as-actions{display:flex;gap:13px;align-items:center;flex-wrap:wrap}.as-text-action{font-size:13px;font-weight:800;display:flex;gap:9px;align-items:center;cursor:pointer;border:0;background:transparent;color:var(--ink);padding:10px}.as-hero-note{position:absolute;right:5vw;bottom:67px;width:155px;font-family:"DM Mono",monospace;font-size:10px;line-height:1.5;color:#5f718c}.as-hero-note:before{content:"";height:45px;border-left:1px solid #c5cfda;display:block;margin-bottom:9px}
        .as-surge{grid-column:2;grid-row:1 / span 2;align-self:stretch;min-height:480px;position:relative;overflow:hidden;margin:-20px -4.8vw -66px 15px;background:#122d5b}.as-surge:before{content:"";position:absolute;inset:-10%;background:radial-gradient(circle at 70% 30%,#ff826d 0 2%,transparent 18%),radial-gradient(circle at 45% 70%,#eb54a2 0 3%,transparent 21%),${gradient};filter:saturate(1.15);opacity:.94}.as-surge:after{content:"";position:absolute;inset:0;background-image:linear-gradient(90deg,rgba(255,255,255,.2) 1px,transparent 1px),linear-gradient(rgba(255,255,255,.16) 1px,transparent 1px);background-size:74px 74px;mask-image:linear-gradient(90deg,transparent,black)}
        .as-orbit{position:absolute;border:1px solid rgba(255,255,255,.65);border-radius:50%;z-index:2;animation:orbit 12s linear infinite}.as-orbit.one{width:540px;height:540px;right:-120px;top:50px}.as-orbit.two{width:340px;height:340px;right:30px;top:150px;animation-direction:reverse;animation-duration:8s}.as-orbit i{position:absolute;width:13px;height:13px;background:#fff;border-radius:50%;top:10%;left:12%;box-shadow:0 0 0 6px rgba(255,255,255,.18)}.as-orbit.two i{background:#122d5b;left:auto;right:10%;top:23%}.as-surge-word{position:absolute;z-index:3;color:white;font-family:Syne,sans-serif;font-weight:800;font-size:clamp(60px,8.5vw,140px);line-height:.8;letter-spacing:-.09em;right:-17px;bottom:23%;transform:rotate(-90deg);transform-origin:center;opacity:.96}.as-pulse-label{position:absolute;z-index:4;bottom:52px;left:38px;color:white;font:10px "DM Mono",monospace;text-transform:uppercase;letter-spacing:.12em}.as-pulse-label span{display:block;width:72px;border-top:1px solid white;margin-bottom:11px}.as-node{position:absolute;z-index:3;width:17px;height:17px;border-radius:50%;background:#fff;animation:drift 4s ease-in-out infinite}.as-node.a{top:24%;left:27%}.as-node.b{top:56%;left:16%;background:#172e5a;animation-delay:-2s}.as-node.c{bottom:18%;right:35%;width:9px;height:9px;animation-delay:-1s}
        .as-ticker{height:70px;color:white;background:var(--ink);display:flex;align-items:center;overflow:hidden;white-space:nowrap}.as-ticker-track{display:flex;gap:34px;animation:scroll 19s linear infinite;font-family:Syne,sans-serif;font-size:23px;font-weight:700;letter-spacing:-.04em}.as-ticker b{color:#ff746e;font-weight:500}.as-ticker i{width:9px;height:9px;border-radius:50%;background:#cf4faf;display:inline-block;align-self:center}
        .as-problem{padding:148px 4.8vw 120px;position:relative}.as-section-label{font:11px "DM Mono",monospace;letter-spacing:.08em;text-transform:uppercase;display:flex;align-items:center;gap:12px;color:#64748b}.as-section-label:before{content:"";display:block;width:28px;border-top:1px solid #e054a7}.as-problem h2{font:700 clamp(40px,5vw,78px)/.99 Syne,sans-serif;letter-spacing:-.075em;max-width:1120px;margin:32px 0 60px}.as-problem h2 em{font-style:normal;color:#e14da4}.as-problem-grid{display:grid;grid-template-columns:1fr 1.75fr;border-top:1px solid var(--line)}.as-problem-grid p{margin:0;padding:24px 20px 10px 0;font-size:14px;line-height:1.55;color:#536783}.as-problem-grid .as-statement{font-size:23px;line-height:1.35;color:var(--ink);padding:21px 0 20px 25px;border-left:1px solid var(--line)}
        .as-model{background:var(--ink);color:white;padding:110px 4.8vw 100px;position:relative}.as-model:before{content:"";width:46%;height:70%;position:absolute;right:-10%;top:2%;background:radial-gradient(circle,#e651a7 0 1%,transparent 1.6%);background-size:21px 21px;opacity:.3;transform:rotate(14deg)}.as-model-head{display:flex;justify-content:space-between;align-items:end;position:relative;z-index:1}.as-model h2{font:700 clamp(40px,5vw,74px)/.98 Syne,sans-serif;letter-spacing:-.07em;margin:22px 0 0;max-width:700px}.as-model p{max-width:300px;color:#c8d2df;font-size:14px;line-height:1.6}.as-force-tabs{display:flex;gap:6px;margin-top:64px;position:relative;z-index:2}.as-force-tabs button{padding:11px 16px;border:1px solid #627492;background:transparent;color:white;font:500 11px "DM Mono",monospace;text-transform:uppercase;cursor:pointer}.as-force-tabs button.active{background:white;color:var(--ink);border-color:white}.as-system{position:relative;z-index:1;min-height:390px;margin-top:32px;border:1px solid #496083;overflow:hidden;background:linear-gradient(135deg,#152f5d,#0e254b)}.as-system-lines{position:absolute;inset:0;background-image:linear-gradient(90deg,rgba(255,255,255,.06) 1px,transparent 1px),linear-gradient(rgba(255,255,255,.06) 1px,transparent 1px);background-size:12.5% 25%}.as-force{position:absolute;padding:19px;background:white;color:var(--ink);width:218px;transition:transform .45s ease}.as-force strong{display:block;font:700 20px Syne,sans-serif;letter-spacing:-.05em}.as-force small{font:10px "DM Mono",monospace;color:#60718a}.as-force.people{left:8%;top:27%}.as-force.agents{right:10%;top:15%;background:${gradient};color:white}.as-force.agents small{color:#fff}.as-force.governance{right:21%;bottom:14%;background:#ffd9d1}.as-route{position:absolute;border:1px solid #f66872;transform-origin:left center}.as-route.r1{left:25%;top:42%;width:37%;transform:rotate(-13deg)}.as-route.r2{left:46%;top:48%;width:28%;transform:rotate(38deg);border-color:#e059ac}.as-route.r3{left:24%;top:57%;width:44%;transform:rotate(13deg);border-color:#bf8dea}.as-system.active-people .people{transform:scale(1.12) translate(10px,-7px)}.as-system.active-agents .agents{transform:scale(1.12) translate(-8px,8px)}.as-system.active-governance .governance{transform:scale(1.12) translate(-9px,-7px)}
        .as-outcomes{padding:125px 4.8vw}.as-outcomes-top{display:flex;justify-content:space-between;align-items:end}.as-outcomes h2{font:700 clamp(42px,5vw,70px)/.97 Syne,sans-serif;letter-spacing:-.075em;max-width:730px;margin:25px 0 0}.as-outcomes-grid{margin-top:70px;display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--ink);border-bottom:1px solid var(--ink)}.as-outcome{min-height:285px;padding:20px 19px;border-right:1px solid var(--ink);position:relative;display:flex;flex-direction:column;justify-content:space-between;transition:background .25s,color .25s}.as-outcome:last-child{border:0}.as-outcome:hover{background:var(--ink);color:white}.as-outcome h3{font:700 29px/.95 Syne,sans-serif;letter-spacing:-.06em;margin:0;max-width:145px}.as-outcome p{font-size:12px;line-height:1.5;margin:0;max-width:200px}.as-outcome svg{position:absolute;right:17px;top:18px;color:#ef5d86}.as-outcome:nth-child(2) svg{color:#b05ae0}.as-outcome:nth-child(3) svg{color:#fd765f}
        .as-work{padding:50px 4.8vw 130px}.as-work-head{display:flex;justify-content:space-between;align-items:center;padding:25px 0;border-top:1px solid var(--line)}.as-work-head h2{font:700 35px Syne,sans-serif;letter-spacing:-.06em;margin:0}.as-case{display:grid;grid-template-columns:1fr 1.3fr;margin-top:20px;min-height:400px;background:#f1eff8;overflow:hidden}.as-case-copy{padding:42px}.as-case-copy h3{font:700 clamp(28px,3vw,47px)/.98 Syne,sans-serif;letter-spacing:-.065em;margin:32px 0 20px}.as-case-copy p{font-size:14px;line-height:1.55;max-width:380px;color:#435979}.as-case-art{position:relative;overflow:hidden;background:#e7619e}.as-case-art:before{content:"";position:absolute;width:520px;height:520px;border-radius:50%;border:62px solid #ffb0ab;top:-160px;left:12%;box-shadow:0 0 0 55px #a75edb,0 0 0 105px #193562}.as-case-art:after{content:"LIVE WORKFLOW / UAE / 01";position:absolute;right:27px;bottom:26px;color:white;font:11px "DM Mono",monospace;letter-spacing:.06em}.as-case-arrow{position:absolute;left:45%;top:45%;width:76px;height:76px;border-radius:50%;background:white;display:grid;place-items:center;color:var(--ink);z-index:2;transition:transform .3s}.as-case:hover .as-case-arrow{transform:scale(1.15) rotate(-25deg)}
        .as-close{background:${gradient};padding:120px 4.8vw 0;color:#fff;position:relative;overflow:hidden}.as-close:before{content:"MOVE";position:absolute;font:800 28vw/.7 Syne,sans-serif;letter-spacing:-.12em;right:-2vw;bottom:-3vw;color:rgba(255,255,255,.13)}.as-close-content{position:relative;z-index:1;max-width:850px}.as-close h2{font:800 clamp(56px,8vw,125px)/.84 Syne,sans-serif;letter-spacing:-.09em;margin:25px 0}.as-close p{font-size:18px;line-height:1.5;max-width:460px}.as-close .as-button{background:var(--ink);margin:22px 0 108px}.as-footer{position:relative;z-index:1;padding:25px 0;border-top:1px solid rgba(255,255,255,.45);display:flex;justify-content:space-between;align-items:end}.as-footer img{width:135px;height:45px;object-fit:contain;object-position:left}.as-footer span{font:10px "DM Mono",monospace}
        @keyframes orbit{to{transform:rotate(360deg)}}@keyframes drift{50%{transform:translate(30px,-25px) scale(.65)}}@keyframes scroll{to{transform:translateX(-45%)}}@media(prefers-reduced-motion:reduce){.agentic-surge *{animation:none!important;transition:none!important}}
        @media(max-width:760px){.as-nav{height:69px;padding:10px 22px}.as-logo{width:121px;transform:scale(1.45)}.as-navlinks,.as-nav>.as-button{display:none}.as-menu{display:block}.as-hero{display:block;min-height:650px;padding:48px 22px 43px}.as-eyebrow{margin-bottom:31px}.as-hero h1{font-size:57px}.as-hero h1 .shift{margin-left:8%}.as-intro{font-size:15px;max-width:92%;position:relative;z-index:4}.as-surge{position:absolute;right:-18%;bottom:0;width:54%;height:265px;min-height:0;margin:0;opacity:.98}.as-surge-word{font-size:79px}.as-hero-note{display:none}.as-actions{position:relative;z-index:4}.as-ticker{height:57px}.as-ticker-track{font-size:17px}.as-problem,.as-outcomes{padding:78px 22px}.as-problem h2{font-size:42px}.as-problem-grid{display:block}.as-problem-grid .as-statement{border-left:0;border-top:1px solid var(--line);padding-left:0;font-size:20px}.as-model{padding:76px 22px}.as-model-head{display:block}.as-model h2{font-size:42px}.as-force-tabs{margin-top:38px;overflow:auto}.as-system{min-height:450px}.as-force{width:154px;padding:14px}.as-force.people{left:5%;top:13%}.as-force.agents{right:4%;top:40%}.as-force.governance{right:17%;bottom:7%}.as-force strong{font-size:16px}.as-route.r1{left:25%;top:28%;width:45%;transform:rotate(29deg)}.as-route.r2{left:45%;top:56%;width:24%;transform:rotate(40deg)}.as-route.r3{left:22%;top:39%;width:45%;transform:rotate(48deg)}.as-outcomes-top{display:block}.as-outcomes h2{font-size:43px}.as-outcomes-grid{grid-template-columns:1fr 1fr;margin-top:42px}.as-outcome{min-height:220px;border-bottom:1px solid var(--ink)}.as-outcome:nth-child(2){border-right:0}.as-work{padding:25px 22px 75px}.as-case{grid-template-columns:1fr}.as-case-copy{padding:27px}.as-case-art{height:270px}.as-close{padding:75px 22px 0}.as-close h2{font-size:62px}.as-close .as-button{margin-bottom:70px}.as-footer{padding:17px 0}.as-footer img{width:110px}}
      `}</style>

      <header className="as-nav">
        <img className="as-logo" src="/__mockup/images/cognirise/logo-blue.svg" alt="Cognirise" />
        <nav className="as-navlinks" aria-label="Primary navigation"><a>What we do</a><a>Platforms</a><a>Industries</a><a>Work</a><a>Insights</a><a>About</a></nav>
        <ArrowButton>Bring us one process</ArrowButton>
        <button className="as-menu" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      </header>
      {menuOpen && <nav style={{padding:"24px 22px",background:"#102b56",color:"white",display:"grid",gap:"17px",fontWeight:700}}><a>What we do</a><a>Platforms</a><a>Industries</a><a>Work</a><a>Insights</a><a>About</a></nav>}

      <section className="as-hero">
        <div className="as-eyebrow">UAE / AI-native advisory & engineering</div>
        <div className="as-hero-copy">
          <h1>AI should <span className="shift">move the</span> <span className="deep">business.</span></h1>
          <p className="as-intro">Cognirise brings senior operators, forward-deployed engineers and governed agents together to move priority work from ambition into production.</p>
          <div className="as-actions"><ArrowButton>Bring us one process</ArrowButton><button className="as-text-action"><Play size={14} fill="currentColor" /> See how we work</button></div>
        </div>
        <div className="as-surge" aria-hidden="true"><div className="as-orbit one"><i /></div><div className="as-orbit two"><i /></div><div className="as-node a" /><div className="as-node b" /><div className="as-node c" /><div className="as-surge-word">SURGE</div><div className="as-pulse-label"><span />activated system</div></div>
        <div className="as-hero-note">Built for UAE enterprises and government where ambition has to become accountable operating change.</div>
      </section>
      <div className="as-ticker"><div className="as-ticker-track"><span>FORWARD-DEPLOYED PEOPLE</span><i /><span>FORWARD-DEPLOYED AGENTS</span><i /><span>GOVERNED DELIVERY</span><i /><span>FORWARD-DEPLOYED PEOPLE</span><i /><span>FORWARD-DEPLOYED AGENTS</span><i /><span>GOVERNED DELIVERY</span></div></div>

      <section className="as-problem">
        <div className="as-section-label">01 / The moment</div>
        <h2>Billions are being spent on AI. <em>Too little work is changing.</em></h2>
        <div className="as-problem-grid"><p>Most AI programmes stall between a promising pilot and a changed operating model.</p><p className="as-statement">Copilots and slideware are not transformation. The work only changes when leaders, engineers and agents are deployed into the work itself.</p></div>
      </section>

      <section className="as-model">
        <div className="as-model-head"><div><div className="as-section-label" style={{color:"#d7e0eb"}}>02 / The Cognirise model</div><h2>Three forces. One accountable team.</h2></div><p>Choose a force to see how it enters the operating system.</p></div>
        <div className="as-force-tabs">{["People","Agents","Governance"].map(force => <button key={force} onClick={() => setActiveForce(force)} className={activeForce === force ? "active" : ""}>{force}</button>)}</div>
        <div className={`as-system active-${activeForce.toLowerCase()}`}>
          <div className="as-system-lines" /><div className="as-route r1" /><div className="as-route r2" /><div className="as-route r3" />
          <div className="as-force people"><strong>Senior operators</strong><small>MAKE THE CALL</small></div>
          <div className="as-force agents"><strong>Governed agents</strong><small>MOVE THE WORK</small></div>
          <div className="as-force governance"><strong>Controls in motion</strong><small>KEEP IT ACCOUNTABLE</small></div>
        </div>
      </section>

      <section className="as-outcomes">
        <div className="as-outcomes-top"><div><div className="as-section-label">03 / What shifts</div><h2>Change the operating equation.</h2></div><ArrowButton>Explore outcomes</ArrowButton></div>
        <div className="as-outcomes-grid">
          {[["01","Reduce cost","Take friction, repetition and avoidable effort out of core workflows."],["02","Create capacity","Put people back on decisions, not administration."],["03","Shorten time","Make a move from test to production with a real delivery team."],["04","De-risk change","Build governance into the work, not around it."]].map(([n,title,body]) => <article className="as-outcome" key={title}><span className="as-index">{n}</span><ArrowDownRight size={23}/><h3>{title}</h3><p>{body}</p></article>)}
        </div>
      </section>

      <section className="as-work">
        <div className="as-work-head"><h2>From mandate to movement.</h2><button className="as-text-action">Selected work <MoveUpRight size={15}/></button></div>
        <article className="as-case"><div className="as-case-copy"><div className="as-kicker">UAE / transformation system</div><h3>Bring one priority process. Leave with a route into production.</h3><p>We start where the operational pressure is already visible: a process, a team, a decision or a service that has to move.</p></div><div className="as-case-art"><div className="as-case-arrow"><ArrowRight size={26}/></div></div></article>
      </section>

      <section className="as-close">
        <div className="as-close-content"><div className="as-kicker">The first move</div><h2>Start with the work.</h2><p>Bring the process that needs to change. In one focused session, we will surface the value, the constraints and the practical route forward.</p><ArrowButton>Book a value scan</ArrowButton></div>
        <footer className="as-footer"><img src="/__mockup/images/cognirise/logo-white.svg" alt="Cognirise" /><span>UAE — Intelligence that moves work.</span></footer>
      </section>
    </main>
  );
}