import { useState } from "react";

const Arrow = () => <svg viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 3l5 5-5 5" /></svg>;

export function GradientEngine() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [sector, setSector] = useState("Banking");
  const [engineOn, setEngineOn] = useState(true);

  const sectorCopy: Record<string, { title: string; copy: string; deployment: string }> = {
    Banking: { title: "Move decisions through the bank.", copy: "Make governed agents useful where the work is dense: servicing, financial crime, credit and operations.", deployment: "A governed operations cell, built around one priority process." },
    Government: { title: "Public value, with control built in.", copy: "Give teams a practical route from policy ambition to auditable, locally governed AI services.", deployment: "A sovereign AI service blueprint and working prototype." },
    Telecoms: { title: "Make the network of work faster.", copy: "Deploy intelligence across service operations, field teams and the complex systems behind the customer moment.", deployment: "A production path for one high-volume service journey." },
    Energy: { title: "Turn operational complexity into action.", copy: "Connect technical knowledge, frontline work and decision rights without adding another detached pilot.", deployment: "An engineering-led operational intelligence sprint." },
  };
  const active = sectorCopy[sector];

  return (
    <main className={`ge ${engineOn ? "is-on" : "is-paused"}`}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap');
        .ge{--ink:#092952;--deep:#071d41;--soft:#edf2fa;--line:#cbd7e8;--violet:#7651e9;--magenta:#d748b9;--coral:#ff795d;--paper:#fbfcff;background:var(--paper);color:var(--ink);font-family:Manrope,system-ui,sans-serif;overflow:hidden;font-size:15px}.ge *{box-sizing:border-box}.ge button{font:inherit}.ge a{color:inherit;text-decoration:none}.ge svg{width:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
        .ge .micro{font:500 10px/1.2 "DM Mono",monospace;letter-spacing:.08em;text-transform:uppercase}.ge .top{height:82px;padding:0 clamp(20px,4vw,64px);display:flex;align-items:center;justify-content:space-between;position:relative;z-index:5;border-bottom:1px solid var(--line);background:rgba(251,252,255,.92);backdrop-filter:blur(12px)}.ge .brand img{display:block;width:220px;height:62px;object-fit:contain;object-position:left center}.ge nav{display:flex;align-items:center;gap:28px;font-size:12px;font-weight:700}.ge nav a:hover{color:var(--magenta)}.ge .nav-cta,.ge .primary{border:0;background:var(--ink);color:#fff;padding:13px 17px;display:inline-flex;gap:17px;align-items:center;font-size:12px;font-weight:800;cursor:pointer;transition:transform .2s,background .2s}.ge .nav-cta:hover,.ge .primary:hover{transform:translateY(-2px);background:#173d70}.ge .primary svg{width:14px}.ge .menu{display:none;border:0;background:none;color:var(--ink);font-size:12px;font-weight:800;padding:10px}
        .ge .hero{position:relative;min-height:670px;padding:clamp(48px,8vw,116px) clamp(20px,8vw,132px) 44px;isolation:isolate;border-bottom:1px solid var(--line)}.ge .hero-copy{position:relative;z-index:2;max-width:960px}.ge .kicker{display:flex;gap:10px;align-items:center;color:#455f86;margin-bottom:24px}.ge .kicker i{height:8px;width:8px;border-radius:50%;background:var(--coral);animation:pulse 1.8s infinite}.ge h1{font-size:clamp(56px,8.8vw,150px);letter-spacing:-.085em;line-height:.84;margin:0;font-weight:800;max-width:1050px}.ge h1 span{display:block;margin-left:clamp(32px,11vw,190px)}.ge .hero-lede{max-width:470px;margin:44px 0 28px 34%;font-size:17px;line-height:1.55;color:#284a76}.ge .hero-actions{margin-left:34%;display:flex;gap:20px;align-items:center}.ge .text-link{font-weight:800;font-size:12px;border-bottom:1px solid var(--ink);padding:5px 0;cursor:pointer;background:none;color:var(--ink)}
        .ge .engine{position:absolute;z-index:1;right:-8%;top:0;width:62%;height:100%;pointer-events:none}.ge .arc{position:absolute;border-radius:50%;border:clamp(42px,5.5vw,88px) solid transparent;background:linear-gradient(135deg,var(--violet),var(--magenta) 55%,var(--coral)) border-box;mask:linear-gradient(#000 0 0) padding-box,linear-gradient(#000 0 0);mask-composite:exclude;animation:turn 12s ease-in-out infinite}.ge .arc-one{width:95%;aspect-ratio:1;right:-29%;top:9%;transform:rotate(-24deg)}.ge .arc-two{width:48%;aspect-ratio:1;right:29%;bottom:-13%;border-width:25px;animation-delay:-5s}.ge .orbit-dot{position:absolute;width:18px;height:18px;border-radius:50%;background:var(--coral);right:24%;top:22%;box-shadow:0 0 0 8px rgba(255,121,93,.14);animation:orbit 5s infinite ease-in-out}.ge .engine-label{position:absolute;right:12%;bottom:52px;width:220px;font:10px/1.5 "DM Mono",monospace;color:#43618c}.ge .hero-index{position:absolute;bottom:35px;left:clamp(20px,4vw,64px);color:#6880a1}
        .ge .marquee{background:var(--deep);color:#fff;overflow:hidden;padding:16px 0;white-space:nowrap}.ge .marquee div{display:inline-block;animation:marquee 22s linear infinite;font:500 11px "DM Mono",monospace;letter-spacing:.05em}.ge .marquee b{color:#fd8b71;margin:0 24px}.ge .thesis{padding:clamp(90px,14vw,190px) clamp(20px,9vw,145px);position:relative}.ge .section-tag{color:#5a7194;margin-bottom:38px}.ge h2{font-size:clamp(39px,5.3vw,80px);letter-spacing:-.07em;line-height:.94;margin:0;max-width:980px}.ge .thesis h2 em{font-style:normal;color:var(--magenta)}.ge .thesis-copy{margin:42px 0 0 40%;max-width:490px;font-size:18px;line-height:1.6;color:#355477}.ge .strikes{position:absolute;right:5%;top:18%;width:170px;height:180px;background:repeating-linear-gradient(135deg,transparent 0 12px,rgba(215,72,185,.9) 13px 16px,transparent 17px 26px);transform:rotate(9deg);opacity:.85}
        .ge .model{background:var(--deep);color:#f7f9ff;padding:110px clamp(20px,6vw,98px);position:relative}.ge .model-head{display:flex;justify-content:space-between;gap:40px;align-items:end;margin-bottom:70px}.ge .model h2{max-width:720px}.ge .model h2 span{color:#fe8c70}.ge .model-head p{max-width:340px;line-height:1.6;color:#b8c9e1;margin:0}.ge .flow{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid rgba(255,255,255,.25);border-bottom:1px solid rgba(255,255,255,.25)}.ge .step{min-height:310px;padding:28px 28px 25px;border-right:1px solid rgba(255,255,255,.25);position:relative;display:flex;flex-direction:column;justify-content:space-between}.ge .step:last-child{border:0}.ge .step .number{font:10px "DM Mono",monospace;color:#a9bdd9}.ge .step h3{font-size:24px;letter-spacing:-.05em;line-height:1;margin:0;max-width:150px}.ge .step p{font-size:13px;line-height:1.55;color:#b8c9e1;margin:0;max-width:190px}.ge .step:hover{background:linear-gradient(145deg,rgba(118,81,233,.6),rgba(215,72,185,.25),rgba(255,121,93,.3))}.ge .ribbon{position:absolute;height:16px;background:linear-gradient(90deg,var(--violet),var(--magenta),var(--coral));top:56%;left:-10%;width:120%;transform:rotate(-6deg);mix-blend-mode:screen;opacity:.95;animation:slide 8s ease-in-out infinite}
        .ge .outcomes{padding:130px clamp(20px,6vw,96px) 100px}.ge .outcome-top{display:grid;grid-template-columns:1fr 1.5fr;gap:50px;margin-bottom:60px}.ge .outcome-top p{font-size:18px;line-height:1.6;max-width:520px;color:#355477;margin:0}.ge .outcome-grid{display:grid;grid-template-columns:1.3fr .7fr .9fr;grid-template-rows:260px 260px;gap:12px}.ge .outcome{border:1px solid var(--line);padding:25px;position:relative;display:flex;flex-direction:column;justify-content:space-between;transition:transform .25s}.ge .outcome:hover{transform:translateY(-6px)}.ge .outcome h3{font-size:clamp(27px,3vw,44px);letter-spacing:-.07em;line-height:.95;margin:0}.ge .outcome p{font-size:13px;line-height:1.5;max-width:220px;margin:0;color:#49658a}.ge .outcome:first-child{grid-row:span 2;background:var(--soft)}.ge .outcome:first-child:after{content:"";position:absolute;width:95%;aspect-ratio:1;border-radius:50%;right:-55%;bottom:-30%;border:40px solid var(--magenta);border-left-color:var(--violet);border-bottom-color:var(--coral)}.ge .outcome:nth-child(3){grid-row:span 2;background:var(--ink);color:#fff}.ge .outcome:nth-child(3) p{color:#bdcee4}.ge .outcome:nth-child(3):after{content:"";width:54px;height:54px;position:absolute;right:25px;bottom:25px;background:linear-gradient(135deg,var(--violet),var(--magenta),var(--coral);clip-path:polygon(50% 0,100% 100%,0 100%)}.ge .outcome:nth-child(4){background:#ff866d;color:var(--deep)}
        .ge .sectors{border-top:1px solid var(--line);padding:110px clamp(20px,6vw,98px)}.ge .sector-nav{margin-top:52px;border-top:1px solid var(--line);display:flex}.ge .sector-nav button{flex:1;background:none;border:0;border-right:1px solid var(--line);padding:20px 10px;color:#537096;font-weight:800;cursor:pointer;text-align:left}.ge .sector-nav button:last-child{border:0}.ge .sector-nav button.active{color:var(--ink);box-shadow:inset 0 4px 0 var(--magenta)}.ge .sector-panel{min-height:340px;display:grid;grid-template-columns:1.25fr .75fr;margin-top:1px;background:var(--soft);position:relative;overflow:hidden}.ge .sector-panel>div{padding:45px}.ge .sector-panel h3{font-size:clamp(36px,4.5vw,67px);line-height:.92;letter-spacing:-.07em;margin:0 0 27px;max-width:650px}.ge .sector-panel p{max-width:490px;font-size:17px;line-height:1.55;color:#365579}.ge .deployment{border-left:1px solid var(--line);display:flex;flex-direction:column;justify-content:end}.ge .deployment strong{font-size:22px;letter-spacing:-.05em;line-height:1.1}.ge .sector-slice{position:absolute;right:-10%;top:-45%;width:40%;aspect-ratio:1;border-radius:50%;border:52px solid var(--coral);border-top-color:var(--violet);border-left-color:var(--magenta);transform:rotate(30deg)}
        .ge .closing{margin:0 12px 12px;background:var(--deep);color:#fff;min-height:570px;padding:clamp(50px,8vw,120px);position:relative;overflow:hidden}.ge .closing h2{font-size:clamp(55px,8vw,126px);max-width:980px;position:relative;z-index:1}.ge .closing h2 span{color:#ff9479}.ge .closing p{position:relative;z-index:1;margin:39px 0 25px;max-width:460px;color:#c2d0e5;line-height:1.6;font-size:17px}.ge .closing .primary{position:relative;z-index:1;background:linear-gradient(100deg,var(--violet),var(--magenta),var(--coral));}.ge .closing .primary:hover{background:linear-gradient(100deg,var(--coral),var(--magenta),var(--violet))}.ge .closing-ring{position:absolute;right:-140px;bottom:-210px;width:690px;aspect-ratio:1;border-radius:50%;border:100px solid transparent;background:linear-gradient(145deg,var(--violet),var(--magenta),var(--coral)) border-box;mask:linear-gradient(#000 0 0) padding-box,linear-gradient(#000 0 0);mask-composite:exclude;animation:turn 14s ease-in-out infinite reverse}.ge footer{padding:28px clamp(20px,4vw,64px) 45px;display:flex;justify-content:space-between;gap:20px;font:10px "DM Mono",monospace;color:#5e789d}.ge .engine-toggle{position:absolute;right:32px;bottom:24px;z-index:3;border:1px solid var(--line);background:var(--paper);padding:10px 12px;color:var(--ink);font:10px "DM Mono",monospace;cursor:pointer}
        @keyframes turn{50%{transform:rotate(28deg) scale(1.05)}}@keyframes orbit{50%{transform:translate(-45px,100px) scale(.55)}}@keyframes marquee{to{transform:translateX(-50%)}}@keyframes pulse{50%{transform:scale(.55);opacity:.4}}@keyframes slide{50%{transform:rotate(-3deg) translateX(4%)}}.is-paused *{animation-play-state:paused!important}
        @media(max-width:800px){.ge .top{height:68px}.ge .brand img{width:126px}.ge nav{display:none}.ge .menu{display:block}.ge .mobile-nav{position:absolute;top:68px;left:0;right:0;background:var(--paper);border-bottom:1px solid var(--line);padding:20px;display:grid;gap:16px}.ge .mobile-nav a{font-weight:800;font-size:14px}.ge .hero{min-height:630px;padding-top:70px}.ge h1{font-size:clamp(57px,17vw,96px);line-height:.86}.ge h1 span{margin-left:9vw}.ge .hero-lede,.ge .hero-actions{margin-left:0}.ge .hero-lede{margin-top:34px;font-size:15px;max-width:330px}.ge .engine{width:100%;right:-40%;opacity:.75;top:22%}.ge .engine-label{display:none}.ge .model{padding-top:78px}.ge .model-head,.ge .outcome-top,.ge .sector-panel{display:block}.ge .model-head p{margin-top:27px}.ge .flow{grid-template-columns:1fr 1fr}.ge .step{min-height:230px;border-bottom:1px solid rgba(255,255,255,.25)}.ge .step:nth-child(2){border-right:0}.ge .outcome-grid{display:flex;flex-direction:column}.ge .outcome{min-height:190px}.ge .outcome:first-child{min-height:270px}.ge .sector-nav{overflow:auto}.ge .sector-nav button{min-width:115px}.ge .sector-panel>div{padding:30px}.ge .deployment{border-left:0;border-top:1px solid var(--line);min-height:150px}.ge .sector-slice{width:70%;right:-35%;top:-20%}.ge .closing{margin:0;min-height:530px}.ge footer{display:block;line-height:2}.ge footer span{display:block}.ge .strikes{opacity:.35;right:-20px}.ge .hero-index{bottom:18px}}
      `}</style>

      <header className="top">
        <a className="brand" href="#top" aria-label="Cognirise home"><img src="/__mockup/images/cognirise/logo-blue.svg" alt="Cognirise" /></a>
        <nav aria-label="Main navigation"><a href="#model">How we work</a><a href="#outcomes">Outcomes</a><a href="#sectors">Industries</a><a href="#platform">CogniOS</a><button className="nav-cta" onClick={() => document.getElementById("start")?.scrollIntoView({ behavior: "smooth" })}>Bring us one process <Arrow /></button></nav>
        <button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}>MENU</button>
        {menuOpen && <div className="mobile-nav"><a href="#model" onClick={() => setMenuOpen(false)}>How we work</a><a href="#outcomes" onClick={() => setMenuOpen(false)}>Outcomes</a><a href="#sectors" onClick={() => setMenuOpen(false)}>Industries</a><a href="#start" onClick={() => setMenuOpen(false)}>Bring us one process</a></div>}
      </header>

      <section className="hero" id="top">
        <div className="hero-copy"><div className="kicker micro"><i /> UAE / BUILT FOR THE WORK AHEAD</div><h1>Make AI<br /><span>move work.</span></h1><p className="hero-lede">Cognirise brings senior operators, forward-deployed engineers and governed agents together to move enterprise and government work from ambition into production.</p><div className="hero-actions"><button className="primary" onClick={() => document.getElementById("start")?.scrollIntoView({ behavior: "smooth" })}>Bring us one process <Arrow /></button><a className="text-link" href="#model">See the operating model</a></div></div>
        <div className="engine" aria-hidden="true"><div className="arc arc-one" /><div className="arc arc-two" /><div className="orbit-dot" /><span className="engine-label">COGNIRISE GRADIENT ENGINE<br />SIGNAL: ACTIVE / DECISIONS IN MOTION</span></div>
        <span className="hero-index micro">01 — Cognirise UAE</span><button className="engine-toggle" onClick={() => setEngineOn(!engineOn)}>{engineOn ? "PAUSE ENGINE" : "START ENGINE"}</button>
      </section>

      <div className="marquee" aria-label="Cognirise capabilities"><div>AI-NATIVE ADVISORY <b>×</b> FORWARD-DEPLOYED ENGINEERING <b>×</b> GOVERNED AGENTS <b>×</b> SOVEREIGN AI <b>×</b> AI-NATIVE ADVISORY <b>×</b> FORWARD-DEPLOYED ENGINEERING <b>×</b> GOVERNED AGENTS <b>×</b> SOVEREIGN AI <b>×</b></div></div>
      <section className="thesis"><div className="strikes" /><div className="section-tag micro">THE DIAGNOSIS / 02</div><h2>AI spend is rising.<br />Too little work is <em>changing.</em></h2><p className="thesis-copy">Pilots multiply. Copilots assist. Slideware circulates. Meanwhile the operating model stays intact. Cognirise starts with the work that matters—and stays close enough to put a better system into use.</p></section>
      <section className="model" id="model"><div className="ribbon" /><div className="model-head"><div><div className="section-tag micro">THE OPERATING MODEL / 03</div><h2>One accountable team.<br /><span>Built in the field.</span></h2></div><p>Not a hand-off from strategy to implementation. A single senior-led team that finds the leverage, builds the system and governs how it runs.</p></div><div className="flow">{[["01","Find the work","Bring one priority process into view."],["02","Build the move","Operators and engineers prototype in the real environment."],["03","Put agents to work","Governed agents act inside the workflow, not beside it."],["04","Scale with control","Architecture, controls and capability hold as adoption grows."]].map(([n,t,p])=><article className="step" key={n}><span className="number">{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
      <section className="outcomes" id="outcomes"><div className="outcome-top"><div><div className="section-tag micro">THE VALUE / 04</div><h2>Change that can be felt in the operation.</h2></div><p>Every engagement is designed around an operational shift, not a technology demonstration. The economic case becomes visible when work starts moving differently.</p></div><div className="outcome-grid"><article className="outcome"><span className="micro">01 / COST</span><h3>Reduce<br />friction.</h3><p>Strip repeatable work out of costly, congested journeys.</p></article><article className="outcome"><span className="micro">02 / CAPACITY</span><h3>Create room.</h3><p>Give people more capacity for judgment and exception work.</p></article><article className="outcome"><span className="micro">03 / SPEED</span><h3>Shorten the distance from decision to action.</h3><p>Put reliable intelligence into the moments that determine pace.</p></article><article className="outcome"><span className="micro">04 / RISK</span><h3>Govern as you go.</h3><p>Design control, traceability and human oversight in from the start.</p></article></div></section>
      <section className="sectors" id="sectors"><div className="section-tag micro">UAE-FIRST / 05</div><h2>Where the work is too important for another pilot.</h2><div className="sector-nav">{Object.keys(sectorCopy).map(name=><button key={name} className={sector===name?"active":""} onClick={()=>setSector(name)}>{name}</button>)}</div><div className="sector-panel"><div><h3>{active.title}</h3><p>{active.copy}</p></div><div className="deployment"><span className="micro">A USEFUL FIRST MOVE</span><strong>{active.deployment}</strong></div><div className="sector-slice" aria-hidden="true" /></div></section>
      <section className="closing" id="start"><div className="section-tag micro">START WITH THE WORK / 06</div><h2>Bring us one<br /><span>process.</span></h2><p>Start with one day. Leave with a sharper problem statement, the shape of a production path, and the people who need to be in the room.</p><button className="primary" onClick={() => alert("A Cognirise team member will help scope the right working session.")}>Book a value scan <Arrow /></button><div className="closing-ring" aria-hidden="true" /></section>
      <footer><span>COGNIRISE — INTELLIGENCE THAT MOVES WORK</span><span>UNITED ARAB EMIRATES / GLOBAL DELIVERY</span><span>© 2026 COGNIRISE</span></footer>
    </main>
  );
}