import React from "react";
import { ExternalLink } from "lucide-react";
import content from "./content.json";
export const pov = content.telecomPov;
type TelecomPov = typeof pov;
type Metric = TelecomPov["metrics"][number] & {
  source?: { url: string; operator: string; date: string; scope: string; measurementBasis: string; attribution: string };
};
type Scenario = TelecomPov["scenarios"][number];
type Department = TelecomPov["departments"][number];
const F = "content.telecomPov";
const DOMAINS = ["Business", "Operations", "Foundations"] as const;
const STAGES = [
  ["detect", "Detect"], ["investigate", "Investigate"], ["propose", "Propose"],
  ["approveExecute", "Approve / execute"], ["verify", "Verify"],
] as const;
const CLASS_LABEL: Record<Metric["classification"], string> = {
  reported: "Reported telco outcome",
  target: "Illustrative KPI target",
  unresolved: "KPI under review",
};
export const TELECOM_FIGURES_NOTE = "Figures are sourced outcomes reported at other operators or illustrative KPI targets. They are not Cognirise delivery results or guarantees; applicability depends on operator context.";

export const MetricsContext = React.createContext<Map<string, Metric>>(new Map());

function MetricChip({ id, detailed = false }: { id: string; detailed?: boolean }) {
  const metrics = React.useContext(MetricsContext);
  const metric = metrics.get(id);
  if (!metric) return null;
  const mi = [...metrics.keys()].indexOf(id);
  const mf = `${F}.metrics.${mi}`;
  return <span className={`tc-metric tc-metric--${metric.classification}`} data-testid={`metric-${metric.id}`} data-metric-classification={metric.classification}>
    <span className="tc-metric-name" data-cms-field={`${mf}.name`}>{metric.name}</span>
    {metric.value && <strong className="tc-metric-value" data-cms-field={`${mf}.value`}>{metric.value}</strong>}
    <span className="tc-metric-class">{CLASS_LABEL[metric.classification]}</span>
    {metric.classification === "reported" && metric.source && <a className="tc-metric-cite" href={metric.source.url} target="_blank" rel="noreferrer">{metric.source.operator}, {metric.source.date}<span className="sr-only"> (opens source)</span> <ExternalLink size={11} aria-hidden="true" /></a>}
    {detailed && <span className="tc-metric-context">{metric.definition} {metric.context}{metric.source ? ` Scope: ${metric.source.scope}. Basis: ${metric.source.measurementBasis}. ${metric.source.attribution}` : ""}</span>}
  </span>;
}

export function MetricList({ ids, detailed }: { ids: string[]; detailed?: boolean }) {
  if (!ids.length) return null;
  return <div className="tc-metric-list">{ids.map((id) => <MetricChip key={id} id={id} detailed={detailed} />)}</div>;
}


export function PriorityMatrix({ candidates }: { candidates: TelecomPov["candidates"] }) {
  const [sel, setSel] = React.useState(candidates[0]?.id);
  const c = candidates.find((x) => x.id === sel) ?? candidates[0];
  const ci = candidates.indexOf(c);
  return <div className="ind-nested-module tc-matrix" id="telecom-prioritisation">
    <div className="ind-kicker">Opportunity prioritisation</div>
    <h3>Illustrative hypotheses, positioned for discussion.</h3>
    <p className="tc-small">Positions are illustrative and agreed with the operator in Innovate. Marker size carries no meaning.</p>
    <div className="tc-matrix-grid">
      <div className="tc-plot" role="group" aria-label="Prioritisation matrix: value against feasibility">
        <span className="tc-q tc-q--tr">Validate first</span><span className="tc-q tc-q--tl">Strategic bets</span><span className="tc-q tc-q--br">Quick checks</span><span className="tc-q tc-q--bl">Revisit later</span>
        <span className="tc-axis tc-axis--x">Feasibility</span><span className="tc-axis tc-axis--y">Value hypothesis</span>
        {candidates.map((x, i) => <button key={x.id} type="button" className={`tc-dot ${x.id === c.id ? "active" : ""}`} style={{ left: `${x.feasibilityPosition}%`, bottom: `${x.valuePosition}%` }} aria-pressed={x.id === c.id} aria-label={`${x.title}: value ${x.valuePosition}, feasibility ${x.feasibilityPosition} (illustrative)`} onClick={() => setSel(x.id)} data-testid={`button-candidate-${x.id}`}>{i + 1}</button>)}
      </div>
      <div className="tc-detail" aria-live="polite">
        <div className="tc-cand-list">{candidates.map((x, i) => <button key={x.id} type="button" aria-pressed={x.id === c.id} className={x.id === c.id ? "active" : ""} onClick={() => setSel(x.id)}><span>{i + 1}</span>{x.title}</button>)}</div>
        <h4 data-cms-field={`${F}.candidates.${ci}.title`}>{c.title}</h4>
        <dl>{([["Value hypothesis", "valueHypothesis"], ["Data readiness", "readiness"], ["Dependencies", "dependencies"], ["Action authority", "authority"], ["Validation needs", "validation"]] as const).map(([label, k]) => <div key={k}><dt>{label}</dt><dd data-cms-field={`${F}.candidates.${ci}.${k}`}>{c[k]}</dd></div>)}</dl>
      </div>
    </div>
  </div>;
}

export function Workforce({ departments }: { departments: Department[] }) {
  const [sel, setSel] = React.useState(departments[0]?.id);
  const d = departments.find((x) => x.id === sel) ?? departments[0];
  const di = departments.indexOf(d);
  return <div className="tc-workforce" id="telecom-workforce">
    <div className="tc-lanes">{DOMAINS.map((domain) => { const list = departments.filter((x) => x.domain === domain); return <div key={domain} className="tc-lane" role="group" aria-label={`${domain} domain, ${list.length} departments`}>
      <h3>{domain} <span>{list.length}</span></h3>
      {list.map((x) => <button key={x.id} type="button" aria-pressed={x.id === d.id} aria-controls="telecom-dept-detail" className={x.id === d.id ? "active" : ""} onClick={() => setSel(x.id)} data-testid={`button-department-${x.id}`}>{x.title}<small>{x.roles.length} roles</small></button>)}
    </div>; })}</div>
    <div className="tc-dept" id="telecom-dept-detail" aria-live="polite">
      <div className="ind-kicker">{d.domain} / selected department</div>
      <h3 data-cms-field={`${F}.departments.${di}.title`}>{d.title}</h3>
      <p className="tc-lead" data-cms-field={`${F}.departments.${di}.challenge`}>{d.challenge}</p>
      <h4>Illustrative functional roles</h4>
      <ul className="tc-roles">{d.roles.map((r, ri) => <li key={r.title}><strong data-cms-field={`${F}.departments.${di}.roles.${ri}.title`}>{r.title}</strong><span data-cms-field={`${F}.departments.${di}.roles.${ri}.body`}>{r.body}</span></li>)}</ul>
      <dl className="tc-dl">{([["Systems", "systems"], ["Actions", "actions"], ["Controls", "controls"]] as const).map(([l, k]) => <div key={k}><dt>{l}</dt><dd data-cms-field={`${F}.departments.${di}.${k}`}>{d[k]}</dd></div>)}</dl>
      <h4>KPIs</h4><MetricList ids={d.metricIds} />
    </div>
  </div>;
}

export function Architecture({ pov, workflowId, setWorkflowId }: { pov: TelecomPov; workflowId?: string; setWorkflowId: (id: string) => void }) {
  const s = pov.scenarios.find((x) => x.id === workflowId);
  const dept = pov.departments.find((d) => d.id === s?.departmentId);
  const layers = [["orchestration", "Domain-limited orchestration"], ["domains", "Business, operations and foundation domains"], ["foundation", "Data and integration foundation"], ["execution", "Authorised execution and handoffs"]] as const;
  return <div className="ind-nested-module tc-arch" id="telecom-architecture">
    <div className="ind-kicker">Telecom application view of Cognirise architecture</div>
    <h3>How a workflow travels through the system.</h3>
    <label className="tc-select">Highlight a workflow <select value={workflowId} onChange={(e) => setWorkflowId(e.target.value)} data-testid="select-architecture-workflow">{pov.scenarios.map((x) => <option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
    <ol className="tc-layers">{layers.map(([k, label]) => <li key={k} className={k === "domains" || k === "orchestration" || k === "execution" ? "lit" : ""}>
      <h4>{label}</h4><p data-cms-field={`${F}.architecture.${k}`}>{pov.architecture[k]}</p>
      {k === "domains" && dept && <div className="tc-route" aria-label="Selected domains">{DOMAINS.map((d) => <span key={d} className={d === dept.domain ? "on" : ""}>{d}{d === dept.domain ? `: ${dept.title}` : ""}</span>)}</div>}
      {k === "execution" && s && <p className="tc-route-note"><strong>Boundary:</strong> {s.boundary}</p>}
    </li>)}</ol>
    <p className="tc-small">Network telemetry is an input; network changes are handed to authorised NEP/NOC owners. No agent holds independent network control or unrestricted shared memory.</p>
  </div>;
}

export function ScenarioWalkthrough({ id, scenarios, departments, selected, onSelect }: { id: string; scenarios: Scenario[]; departments: Department[]; selected?: string; onSelect?: (id: string) => void }) {
  const [local, setLocal] = React.useState(scenarios[0]?.id);
  const current = selected ?? local;
  const s = scenarios.find((x) => x.id === current) ?? scenarios[0];
  const [stage, setStage] = React.useState(0);
  const tabs = React.useRef<(HTMLButtonElement | null)[]>([]);
  if (!s) return null;
  const pick = (v: string) => { setStage(0); onSelect ? onSelect(v) : setLocal(v); };
  const onKey = (e: React.KeyboardEvent, i: number) => {
    let n = i;
    if (e.key === "ArrowRight") n = (i + 1) % STAGES.length; else if (e.key === "ArrowLeft") n = (i - 1 + STAGES.length) % STAGES.length; else if (e.key === "Home") n = 0; else if (e.key === "End") n = STAGES.length - 1; else return;
    e.preventDefault(); setStage(n); tabs.current[n]?.focus();
  };
  const dept = departments.find((d) => d.id === s.departmentId);
  return <div className="tc-walk" id={id}>
    {scenarios.length > 1 && <div className="tc-scen-list" role="group" aria-label="Choose a workflow">{scenarios.map((x) => <button key={x.id} type="button" aria-pressed={x.id === s.id} className={x.id === s.id ? "active" : ""} onClick={() => pick(x.id)} data-testid={`button-scenario-${id}-${x.id}`}>{x.title}</button>)}</div>}
    <div className="tc-walk-body">
      <div className="tc-walk-meta"><span className="tc-tag">Illustrative workflow</span><h4>{s.title}</h4><p>{dept?.title}</p><dl className="tc-dl"><div><dt>Owner</dt><dd>{s.owner}</dd></div><div><dt>Approval boundary</dt><dd>{s.boundary}</dd></div><div><dt>Audit and recovery</dt><dd>{s.auditRecovery}</dd></div></dl><MetricList ids={s.metricIds} /></div>
      <div>
        <div className="tc-stages" role="tablist" aria-label={`${s.title} stages`}>{STAGES.map(([k, l], i) => <button key={k} ref={(el) => { tabs.current[i] = el; }} role="tab" id={`${id}-tab-${k}`} aria-selected={stage === i} aria-controls={`${id}-panel`} tabIndex={stage === i ? 0 : -1} className={stage === i ? "active" : ""} onClick={() => setStage(i)} onKeyDown={(e) => onKey(e, i)}><span>0{i + 1}</span>{l}</button>)}</div>
        <div className="tc-stage-panel" role="tabpanel" id={`${id}-panel`} aria-labelledby={`${id}-tab-${STAGES[stage][0]}`}><p>{s.stages[STAGES[stage][0]]}</p>
          <div className="tc-stage-nav"><button type="button" disabled={stage === 0} onClick={() => setStage(stage - 1)}>Previous stage</button><button type="button" disabled={stage === STAGES.length - 1} onClick={() => setStage(stage + 1)}>Next stage</button></div></div>
      </div>
    </div>
  </div>;
}


const industryStyles = `
  .industry{--ink:#102957;--deep:#071936;--paper:#fdfbf7;--soft:#eef0f5;--line:#cbd3e1;--violet:#7659df;--pink:#db509e;--coral:#ff775d;background:var(--paper);color:var(--ink);font-family:Inter,sans-serif;overflow-x:hidden}.industry *{box-sizing:border-box}.industry h1,.industry h2,.industry h3,.industry h4{font-family:Comfortaa,sans-serif}.industry a{color:inherit}.industry :focus-visible{outline:3px solid var(--coral);outline-offset:4px}.ind-kicker{font-size:10px;letter-spacing:.13em;text-transform:uppercase;font-weight:700;display:flex;align-items:center;gap:10px}.ind-kicker:before{content:"";width:25px;height:2px;background:linear-gradient(90deg,var(--violet),var(--pink),var(--coral))}
  .ind-hero{padding:34px 4.8vw 50px;display:grid;grid-template-columns:.88fr 1.12fr;gap:5vw;align-items:end;min-height:690px}.ind-copy{padding-bottom:25px}.ind-copy h1{font-size:clamp(50px,6.2vw,96px);line-height:.94;letter-spacing:-.075em;margin:32px 0 28px}.ind-thesis-dash{display:inline-block;letter-spacing:0;margin-inline:.06em}.ind-copy p{max-width:570px;color:#405677;font-size:17px;line-height:1.65}.ind-image{height:610px;position:relative;overflow:hidden;clip-path:polygon(10% 0,100% 0,100% 91%,0 100%,0 12%);background:var(--deep)}.ind-image img{width:100%;height:100%;object-fit:cover;animation:ind-reveal 1s ease both}.ind-image:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(7,25,54,.46),transparent 50%),linear-gradient(0deg,rgba(7,25,54,.5),transparent 48%)}.ind-image span{position:absolute;z-index:1;left:32px;bottom:30px;color:white;text-transform:uppercase;font-size:10px;letter-spacing:.13em}
   .ind-opportunity{margin:0 4.8vw;padding:90px 6vw;background:var(--deep);color:white;display:grid;grid-template-columns:.72fr 1.28fr;gap:8vw;align-items:start;position:relative;overflow:hidden}.ind-opportunity:after{content:"OPPORTUNITY";position:absolute;right:-10px;bottom:-12px;font:600 9vw/.8 Comfortaa;color:#ffffff0b}.ind-opportunity>*{position:relative;z-index:1}.ind-opportunity h2,.ind-pressure>div>h2,.ind-capabilities h2,.ind-evidence h2,.ind-gcc h2,.ind-sources h2{font-size:clamp(42px,5vw,72px);line-height:.98;letter-spacing:-.07em;margin:22px 0}.ind-opportunity p{font-size:clamp(20px,2vw,28px);line-height:1.55;color:#d7dfed;margin:0}.ind-opportunity-detail{display:block;margin-top:40px;padding-top:35px;border-top:1px solid #ffffff30}.ind-opportunity-detail strong{display:block;font-size:22px;line-height:1.45;color:#fff}.ind-opportunity-detail em{font-size:19px}.ind-opportunity-rich p{font-size:clamp(20px,2vw,28px)}.ind-opportunity-rich h2,.ind-opportunity-rich h3{margin:0 0 18px;color:#fff}.ind-opportunity-rich ul,.ind-opportunity-rich ol{margin:24px 0 0;padding-left:24px;color:#d7dfed;font-size:18px;line-height:1.6}.ind-opportunity-rich li+li{margin-top:10px}
  .ind-pressure{padding:130px 4.8vw 110px;display:grid;grid-template-columns:.72fr 1.28fr;gap:8vw}.ind-pressure-list{border-top:1px solid var(--ink)}.ind-pressure article{display:grid;grid-template-columns:55px 1fr;padding:28px 0;border-bottom:1px solid var(--line)}.ind-pressure article>span{color:var(--pink);font-size:10px;letter-spacing:.12em}.ind-pressure h3,.ind-pressure h4{font-size:24px;letter-spacing:-.04em;margin:0 0 9px}.ind-pressure p{color:#506583;line-height:1.6;margin:0;max-width:560px}.ind-nested-module{grid-column:1/-1;margin-top:24px;padding-top:44px;border-top:1px solid var(--line)}.ind-nested-module>h3{font-size:clamp(28px,3vw,42px);letter-spacing:-.06em;margin:18px 0 28px}.ind-convictions{background:var(--soft);padding:44px}
  .ind-capabilities{padding:110px 4.8vw;background:var(--soft)}.ind-capabilities-head{display:grid;grid-template-columns:.72fr 1.28fr;gap:8vw}.ind-capabilities-head>p{max-width:500px;color:#536887;line-height:1.6;align-self:end}.ind-disclosure-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;margin-top:50px;border:1px solid var(--line);background:var(--line)}.ind-disclosure-item{min-width:0;background:var(--paper)}.ind-disclosure-trigger{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:start;width:100%;min-height:190px;border:0;background:transparent;padding:30px;text-align:left;color:var(--ink);cursor:pointer}.ind-disclosure-trigger span{color:var(--pink);font-size:10px;letter-spacing:.12em}.ind-disclosure-trigger h3{grid-column:1/-1;font-size:25px;line-height:1.15;letter-spacing:-.04em;margin:5px 0 0}.ind-disclosure-trigger svg{grid-column:2;grid-row:1;transition:transform .2s ease}.ind-disclosure-item.active .ind-disclosure-trigger svg{transform:rotate(180deg)}.ind-disclosure-panel{display:none;padding:0 30px 30px;overflow:visible}.ind-disclosure-item.active .ind-disclosure-panel{display:block}.ind-disclosure-panel p{margin:0;color:#506583;line-height:1.6}.ind-disclosure-panel ul{margin:18px 0 0;padding-left:20px;color:#405677;line-height:1.55}.ind-capabilities .ind-nested-module .ind-disclosure-grid{margin-top:0}.ind-education-imagery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.ind-education-imagery figure{margin:0;background:var(--paper)}.ind-education-imagery img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}.ind-education-imagery figcaption{padding:13px 16px;color:#405677;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.1em}
   .ind-evidence{padding:120px 4.8vw}.ind-evidence-head{display:flex;justify-content:space-between;align-items:end;gap:40px}.ind-evidence-head p{max-width:400px;color:#536887;line-height:1.6}.ind-table{width:100%;border-collapse:collapse;margin-top:45px;text-align:left}.ind-table thead th{font-size:9px;text-transform:uppercase;letter-spacing:.13em;color:#6f7d94;border-block:1px solid var(--ink);padding:16px}.ind-table td,.ind-table tbody th{padding:22px 16px;border-bottom:1px solid var(--line);vertical-align:top;line-height:1.5}.ind-table tbody th{font:600 18px Comfortaa;text-align:left}.ind-table td:first-of-type{color:#db509e;font-weight:700}.ind-table tbody th a{display:inline-flex;align-items:center;gap:5px;color:inherit;text-decoration:underline;text-decoration-color:var(--pink);text-decoration-thickness:2px;text-underline-offset:4px}.ind-use-description{margin:12px 0 0;color:#506583;font:400 14px/1.55 Inter,sans-serif}.ind-application-group{margin-top:38px}.ind-application-group h4{font-size:21px;margin:0 0 -22px}.ind-inline-sources{display:flex;flex-wrap:wrap;gap:8px 14px;margin-top:12px}.ind-inline-sources a{display:inline-flex;align-items:center;gap:4px;color:var(--pink);font-size:12px;text-decoration:underline}.ind-source-table{font-size:14px}.ind-source-table td,.ind-source-table tbody th{font-size:13px}.ind-source-table td:first-of-type{color:#405677;font-weight:400}.ind-source-table td:nth-of-type(3),.ind-source-table td:nth-of-type(4){min-width:220px;color:#405677;font-weight:400}.ind-sources-introduction{max-width:760px;margin:28px 0 0;color:#506583;line-height:1.65}
  .ind-perspective{background:var(--deep);color:white}.ind-support{margin:0 4.8vw;display:grid;grid-template-columns:1fr 1fr;position:relative}.ind-support>div{padding:70px 7%;position:relative}.ind-support>div:first-child{border-right:1px solid #ffffff30}.ind-support h2{font-size:clamp(35px,4vw,58px);letter-spacing:-.065em;line-height:1;margin:20px 0}.ind-support h3{font-size:22px;line-height:1.4;color:#fff}.ind-support p{color:#d7dfed;line-height:1.65}.ind-support strong{display:block;font:600 clamp(25px,3vw,42px)/1.1 Comfortaa;margin:20px 0}.ind-support-detail{margin-top:40px;padding-top:30px;border-top:1px solid #ffffff30}.ind-roadmap{margin:0 4.8vw;padding:0 7% 90px}.ind-roadmap>h3{font-size:clamp(30px,3.5vw,50px);letter-spacing:-.055em;line-height:1.05;margin:20px 0 35px}.ind-stage-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:#ffffff30}.ind-stage{min-width:0;background:#0b2246}.ind-stage-trigger{width:100%;min-height:145px;border:0;padding:24px;background:transparent;color:#fff;text-align:left;cursor:pointer}.ind-stage-trigger span{display:block;color:var(--pink);font-size:11px;font-weight:700;letter-spacing:.1em}.ind-stage-trigger h4{margin:12px 0 0;font-size:20px}.ind-stage-trigger svg{float:right;margin-top:-22px}.ind-stage-panel{display:none;padding:0 24px 24px;overflow:visible}.ind-stage.active .ind-stage-panel{display:block}.ind-stage-panel p{margin:0;color:#d7dfed;line-height:1.6}
   .ind-gcc{background:var(--soft);padding:110px 4.8vw;display:grid;grid-template-columns:1fr 1fr;gap:8vw}.ind-gcc p{font-size:20px;line-height:1.55;color:#405677;align-self:end;border-top:1px solid var(--ink);padding-top:24px}.ind-rich-blocks{color:#405677;line-height:1.65}.ind-rich-blocks p{margin:0 0 24px}.ind-rich-blocks p:last-child{margin-bottom:0}.ind-rich-blocks h2,.ind-rich-blocks h3{margin:0 0 16px;color:var(--ink);letter-spacing:-.04em}.ind-rich-blocks h2{font-size:30px}.ind-rich-blocks h3{font-size:22px}.ind-rich-blocks ul,.ind-rich-blocks ol{margin:0 0 24px;padding-left:24px}.ind-rich-blocks li+li{margin-top:8px}.ind-market-rich{border-top:1px solid var(--ink);padding-top:24px;font-size:20px}.ind-market-rich h2,.ind-market-rich h3{font-size:24px}.ind-next-action-rich{color:#d7dfed;max-width:820px}.ind-next-action-rich h2,.ind-next-action-rich h3{color:#fff}.ind-next-action-rich h2{font-size:clamp(45px,6vw,88px);line-height:.94;letter-spacing:-.08em}.ind-next-action-rich p{line-height:1.6}.ind-next-action-rich ul,.ind-next-action-rich ol{padding-left:24px;line-height:1.6}.ind-preserve-lines{white-space:normal}.ind-leadership-test{margin-top:30px;padding-top:20px;border-top:2px solid var(--coral);font-weight:bold;color:var(--ink);line-height:1.55}.ind-leadership-test span{display:block;margin-bottom:8px;color:var(--pink);font-size:10px;text-transform:uppercase;letter-spacing:.12em}
  .ind-sources{padding:110px 4.8vw}.ind-sources-list{margin-top:38px;border-top:1px solid var(--ink)}.ind-source{display:grid;grid-template-columns:1.3fr .8fr .6fr 30px;gap:20px;padding:19px 8px;border-bottom:1px solid var(--line);text-decoration:none;align-items:center}.ind-source span{font-size:12px;color:#647491}.ind-source strong{font-family:Comfortaa}.ind-source:hover strong{color:var(--pink)}.ind-case-link{display:inline-flex;gap:8px;align-items:center;margin-top:34px;border-bottom:1px solid var(--pink);padding-bottom:5px;font-size:14px;font-weight:700;text-decoration:none}
  .ind-cta{background:var(--deep);color:white;padding:95px 4.8vw;display:grid;grid-template-columns:1.3fr .7fr;gap:40px;align-items:end;position:relative;overflow:hidden}.ind-cta:before{content:"SIGNAL";position:absolute;right:-10px;bottom:-20px;font:600 16vw/.7 Comfortaa;color:#ffffff0b}.ind-cta>*{position:relative}.ind-cta h2{font-size:clamp(45px,6vw,88px);line-height:.94;letter-spacing:-.08em;margin:20px 0}.ind-cta p{color:#d7dfed;line-height:1.6}.ind-cta aside{border-left:2px solid var(--coral);padding-left:25px}.ind-cta aside a{display:block;margin-bottom:24px;font-weight:700}
  .industry--network .ind-hero{grid-template-columns:1.05fr .95fr}.industry--network .ind-image{clip-path:polygon(0 7%,92% 0,100% 100%,8% 94%)}.industry--journey .ind-hero{grid-template-columns:.74fr 1.26fr}.industry--journey .ind-image{clip-path:polygon(5% 0,100% 7%,94% 100%,0 92%)}.industry--field .ind-hero{grid-template-columns:1fr 1fr}.industry--field .ind-image{height:680px;clip-path:polygon(14% 0,100% 0,94% 100%,0 92%)}.industry--factory .ind-hero{grid-template-columns:1.12fr .88fr}.industry--factory .ind-image{height:560px;clip-path:polygon(0 0,100% 10%,93% 100%,8% 92%)}
  @keyframes ind-reveal{from{clip-path:inset(0 100% 0 0);transform:scale(1.05)}to{clip-path:inset(0);transform:none}}@media(min-width:761px) and (max-width:1050px){.ind-disclosure-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.ind-hero,.industry--network .ind-hero,.industry--journey .ind-hero,.industry--field .ind-hero,.industry--factory .ind-hero{display:flex;flex-direction:column;align-items:stretch;min-height:0;padding:34px 21px 36px}.ind-copy h1{font-size:51px}.ind-image,.industry--field .ind-image,.industry--factory .ind-image{height:430px}.ind-opportunity{display:block;margin:0;padding:70px 21px}.ind-opportunity p{margin-top:35px}.ind-pressure{display:block;padding:85px 21px}.ind-pressure-list{margin-top:40px}.ind-pressure article{grid-template-columns:38px 1fr}.ind-convictions{padding:28px 22px}.ind-capabilities{padding:82px 21px}.ind-capabilities-head{display:block}.ind-capabilities-head>p{margin-top:26px}.ind-disclosure-grid,.ind-stage-grid,.ind-education-imagery-grid{grid-template-columns:1fr;margin-top:35px}.ind-disclosure-trigger{min-height:0;padding:26px 24px}.ind-disclosure-panel{padding:0 24px 28px}.ind-evidence{padding:85px 21px}.ind-evidence-head{display:block}.ind-table,.ind-table tbody,.ind-table tr,.ind-table td,.ind-table tbody th{display:block}.ind-table thead{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}.ind-table tr{border-bottom:1px solid var(--line);padding:18px 0}.ind-table td,.ind-table tbody th{border:0;padding:5px 0}.ind-table td:before,.ind-table tbody th:before{content:attr(data-label);display:block;font:700 9px Inter;text-transform:uppercase;letter-spacing:.12em;color:#70809a;margin-bottom:4px}.ind-application-group h4{margin-bottom:-12px}.ind-support{display:block;margin:0}.ind-support>div{padding:58px 21px}.ind-support>div:first-child{border-right:0;border-bottom:1px solid #ffffff30}.ind-roadmap{margin:0;padding:0 21px 65px}.ind-gcc{display:block;padding:82px 21px}.ind-gcc p{margin-top:38px}.ind-sources{padding:82px 21px}.ind-source{grid-template-columns:1fr 24px}.ind-source span{grid-column:1}.ind-source svg{grid-column:2;grid-row:1}.ind-cta{display:block;padding:78px 21px}.ind-cta aside{margin-top:45px}}@media(prefers-reduced-motion:reduce){.industry *,.industry *:before,.industry *:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
const telecomStyles = `
.telecom :is(h1,h2,h3,h4,p,dd,dt,td,th,button,a){overflow-wrap:anywhere;min-width:0}
.telecom :is(section,div,li,dl,figure){min-width:0}
.telecom .sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
.tc-hero-actions{display:flex;flex-wrap:wrap;gap:22px;align-items:center;margin-top:30px}.tc-anchor{display:inline-flex;gap:6px;align-items:center;font-weight:700;border-bottom:2px solid var(--coral);padding:8px 0;text-decoration:none}
.tc-head{display:grid;grid-template-columns:.72fr 1.28fr;gap:8vw;align-items:end}.tc-head p{color:#536887;line-height:1.6;max-width:560px}
.tc-pools{grid-column:1/-1;margin-top:20px;padding-top:50px;border-top:1px solid #ffffff30}.tc-opportunity .tc-pools p{font-size:16px;line-height:1.6}.tc-opportunity .tc-head p,.tc-opportunity .tc-pool p{color:#c4cee0}.tc-opportunity .tc-note{background:#ffffff10;color:#e6ebf4;border-left-color:var(--coral)}.tc-opportunity .tc-pool-list{border-top-color:#ffffff60}.tc-opportunity .tc-pool{border-bottom-color:#ffffff26}.tc-opportunity .tc-small{color:#9fb0cc}.tc-opportunity .tc-metric-cite{color:#ffb4d9}.tc-pools h3{color:#fff;font-size:clamp(36px,4.4vw,64px);line-height:1;letter-spacing:-.065em;margin:20px 0}
.tc-note{margin:30px 0 0;padding:14px 18px;border-left:3px solid var(--violet);background:var(--soft);color:#405677;font-size:14px;line-height:1.55;max-width:860px}
.tc-pool-list{list-style:none;padding:0;margin:40px 0 0;border-top:1px solid var(--ink)}.tc-pool{display:grid;grid-template-columns:55px 1.1fr 120px 1fr;gap:24px;padding:26px 0;border-bottom:1px solid var(--line);align-items:start}.tc-pool h4{color:#fff;font-size:22px;letter-spacing:-.04em;margin:0 0 8px}.tc-pool p{margin:0;color:#506583;line-height:1.6}.tc-num{color:var(--pink);font-size:11px;letter-spacing:.12em;font-weight:700}.tc-rail{height:2px;margin-top:14px;background:linear-gradient(90deg,var(--violet),var(--pink),var(--coral))}
.tc-small{font-size:13px;color:#647491;line-height:1.55;margin:16px 0 0}.tc-small--inv{color:#c4cee0}.tc-small--inv a{color:#fff;font-weight:700;display:inline-flex;align-items:center;gap:4px}
.tc-metric-list{display:flex;flex-wrap:wrap;gap:8px}.tc-metric{display:inline-flex;flex-wrap:wrap;align-items:baseline;gap:4px 8px;padding:7px 10px;border:1px solid var(--line);background:var(--paper);font-size:13px;line-height:1.35;max-width:100%;color:var(--ink)}.tc-metric-value{font-family:Comfortaa;font-size:15px}.tc-metric-class{font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;padding:2px 6px}.tc-metric--reported{border-left:3px solid var(--ink)}.tc-metric--reported .tc-metric-class{background:var(--ink);color:#fff}.tc-metric--target{border-style:dashed}.tc-metric--target .tc-metric-class{border:1px dashed var(--pink);color:#a3306f}.tc-metric--unresolved .tc-metric-class{color:#647491;border:1px solid var(--line)}.tc-metric-cite{color:var(--pink);font-size:12px;text-decoration:underline;display:inline-flex;align-items:center;gap:3px}.tc-metric-context{flex-basis:100%;color:#506583;font-size:12.5px}
.tc-matrix-grid{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:24px}.tc-plot{position:relative;aspect-ratio:1;border-left:2px solid var(--ink);border-bottom:2px solid var(--ink);background:linear-gradient(var(--line),var(--line)) 50% 0/1px 100% no-repeat,linear-gradient(var(--line),var(--line)) 0 50%/100% 1px no-repeat;margin:0 0 30px 30px}.tc-q{position:absolute;font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#647491;padding:10px}.tc-q--tr{right:0;top:0;color:var(--pink)}.tc-q--tl{left:0;top:0}.tc-q--br{right:0;bottom:0}.tc-q--bl{left:0;bottom:0}.tc-axis{position:absolute;font-size:11px;color:#405677;font-weight:700}.tc-axis--x{bottom:-26px;right:0}.tc-axis--y{left:-28px;top:0;writing-mode:vertical-rl;transform:rotate(180deg)}
.tc-dot{position:absolute;width:44px;height:44px;margin:0 0 -22px -22px;border-radius:50%;border:2px solid var(--ink);background:var(--paper);font-weight:700;color:var(--ink);cursor:pointer;transition:transform .2s ease}.tc-dot.active{background:var(--ink);color:#fff;box-shadow:0 0 0 4px var(--paper),0 0 0 6px var(--coral)}
.tc-cand-list,.tc-scen-list{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:22px}.tc-cand-list button,.tc-scen-list button,.tc-range-track button,.tc-stages button,.tc-lane button{min-height:44px;border:1px solid var(--line);background:var(--paper);color:var(--ink);padding:8px 12px;text-align:left;cursor:pointer;font:600 13px Inter}.tc-cand-list button span{color:var(--pink);margin-right:6px}.tc-cand-list .active,.tc-scen-list .active,.tc-lane .active,.tc-stages .active{background:var(--ink);color:#fff;border-color:var(--ink)}
.tc-detail h4,.tc-dept h3,.tc-walk h4{font-size:26px;letter-spacing:-.04em;margin:0 0 14px}.tc-detail dl,.tc-dl{margin:0;display:grid;gap:0}.tc-detail dl div,.tc-dl div{display:grid;grid-template-columns:150px 1fr;gap:16px;padding:12px 0;border-top:1px solid var(--line)}dt{font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#647491}dd{margin:0;color:#405677;line-height:1.55}
.tc-workforce{display:grid;grid-template-columns:1.1fr 1fr;gap:1px;margin-top:50px;background:var(--line);border:1px solid var(--line);scroll-margin-top:110px}.tc-lanes{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line)}.tc-lane{background:var(--paper);padding:20px;display:flex;flex-direction:column;gap:6px}.tc-lane h3{font-size:16px;margin:0 0 10px;display:flex;justify-content:space-between}.tc-lane h3 span{color:var(--pink);font-family:Inter}.tc-lane button{display:flex;flex-direction:column;gap:2px}.tc-lane small{font-weight:400;font-size:11px;opacity:.75}
.tc-dept{background:var(--paper);padding:32px}.tc-lead{color:#405677;line-height:1.6;font-size:17px;max-width:720px}.tc-dept h4,.tc-arch h4{font-size:14px;letter-spacing:0;margin:22px 0 10px;font-family:Inter;text-transform:uppercase;font-size:11px;letter-spacing:.1em;color:#647491}.tc-roles{list-style:none;padding:0;margin:0;border-top:1px solid var(--line)}.tc-roles li{padding:10px 0;border-bottom:1px solid var(--line);display:grid;gap:3px}.tc-roles span{color:#506583;font-size:14px;line-height:1.5}
.tc-select{display:inline-flex;flex-wrap:wrap;gap:10px;align-items:center;font-weight:700;font-size:13px}.tc-select select,.tc-filters select,.tc-filters input{min-height:44px;border:1px solid var(--ink);background:var(--paper);padding:0 12px;font:14px Inter;color:var(--ink)}
.tc-layers{list-style:none;padding:0;margin:24px 0 0;display:grid;gap:0;border-top:1px solid var(--ink)}.tc-layers li{padding:22px 0 22px 26px;border-bottom:1px solid var(--line);position:relative}.tc-layers li.lit:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:linear-gradient(180deg,var(--violet),var(--pink),var(--coral))}.tc-layers h4{margin:0 0 6px!important}.tc-layers p{margin:0;color:#405677;line-height:1.55}.tc-route{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.tc-route span{padding:6px 10px;border:1px solid var(--line);font-size:13px}.tc-route .on{border-color:var(--pink);color:#a3306f;font-weight:700}.tc-route-note{margin-top:10px!important}
.tc-walk{margin-top:36px}.tc-walk-body{display:grid;grid-template-columns:.9fr 1.1fr;gap:40px;border-top:1px solid var(--ink);padding-top:28px}.tc-walk-meta p{color:#506583}.tc-walk-meta .tc-metric-list{margin-top:16px}.tc-tag{display:inline-block;font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;border:1px dashed var(--pink);color:#a3306f;padding:3px 7px;margin-bottom:10px}
.tc-stages{display:flex;flex-wrap:wrap;gap:4px}.tc-stages button span{color:var(--pink);margin-right:6px;font-size:11px}.tc-stages .active span{color:#ffb4a6}.tc-stage-panel{padding:24px 0;border-bottom:1px solid var(--line)}.tc-stage-panel p{font-size:17px;line-height:1.6;color:#405677;margin:0}.tc-stage-nav{display:flex;gap:10px;margin-top:18px}.tc-stage-nav button,.tc-empty button{min-height:44px;padding:0 14px;border:1px solid var(--ink);background:transparent;color:var(--ink);font-weight:700;cursor:pointer}.tc-stage-nav button:disabled{opacity:.4;cursor:default}
.tc-adapt{display:grid;grid-template-columns:repeat(2,1fr);border-top:1px solid var(--ink)}.tc-adapt article{padding:24px 24px 24px 0;border-bottom:1px solid var(--line)}.tc-adapt h4{font-size:20px;margin:0 0 8px}.tc-adapt p{color:#506583;line-height:1.55;margin:0 0 10px}.tc-constraint{font-size:14px}
.tc-expand{width:100%;display:flex;justify-content:space-between;align-items:center;min-height:60px;border:0;border-block:1px solid var(--ink);background:transparent;font:600 22px Comfortaa;color:var(--ink);cursor:pointer;text-align:left}.tc-expand[aria-expanded=true] svg{transform:rotate(180deg)}.tc-filters{display:flex;flex-wrap:wrap;gap:16px;align-items:center;margin-top:22px;font-size:13px;font-weight:700}.tc-filters label{display:inline-flex;gap:8px;align-items:center}.tc-out td:first-of-type{color:#405677;font-weight:400}.tc-empty{padding:30px 0;color:#506583}
.tc-range{margin:0 4.8vw;padding:90px 7% 50px}.tc-range h2{font-size:clamp(35px,4vw,58px);letter-spacing:-.065em;line-height:1;margin:20px 0}.tc-range-track{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;margin-top:32px;background:#ffffff30;position:relative}.tc-range-track button{background:#0b2246;color:#fff;border:0;min-height:90px;display:flex;flex-direction:column;gap:8px;justify-content:flex-end}.tc-range-track button span{color:var(--pink);font-size:11px}.tc-range-track .active{background:#fdfbf7;color:var(--ink)}.tc-range-detail{padding:30px 0}.tc-range-detail h3{font-size:28px;margin:0 0 10px}.tc-range-detail p{color:#d7dfed;line-height:1.6}.tc-range-detail dt{color:#9fb0cc}.tc-range-detail dd{color:#e6ebf4}.tc-range-detail .tc-dl div{border-color:#ffffff30}
.tc-delivery{margin:0 4.8vw;padding:0 7% 90px}.tc-delivery h3{font-size:clamp(28px,3vw,42px);letter-spacing:-.055em;margin:18px 0 28px}.tc-delivery ol{list-style:none;padding:0;margin:0;display:grid;grid-template-columns:repeat(4,1fr);border-top:2px solid;border-image:linear-gradient(90deg,var(--violet),var(--pink),var(--coral)) 1}.tc-delivery li{padding:20px 20px 0 0}.tc-delivery li span{color:var(--pink);font-size:11px;font-weight:700}.tc-delivery h4{font-size:20px;margin:8px 0}.tc-delivery li p{color:#d7dfed;line-height:1.55;margin:0}
.tc-market p{font-size:18px!important}.tc-market p+p{margin-top:20px}.tc-sub{font-size:24px;margin:44px 0 0}.ind-sources .tc-metric-list{margin-top:18px}.tc-entry{list-style:none;padding:0;margin:24px 0 0;display:grid;gap:12px;color:#d7dfed;max-width:760px}.tc-entry li{display:grid;gap:4px;padding-top:12px;border-top:1px solid #ffffff30}.tc-entry strong{color:#fff}
.telecom [id]{scroll-margin-top:110px}
@media(max-width:900px){.tc-head,.tc-matrix-grid,.tc-workforce,.tc-walk-body{grid-template-columns:1fr}.tc-pool{grid-template-columns:40px 1fr}.tc-rail{display:none}.tc-pool .tc-metric-list{grid-column:2}.tc-lanes{grid-template-columns:1fr}.tc-adapt,.tc-delivery ol{grid-template-columns:1fr}.tc-range-track{grid-template-columns:1fr}.tc-range-track button{min-height:52px;flex-direction:row;justify-content:flex-start;align-items:center}.tc-detail dl div,.tc-dl div{grid-template-columns:1fr;gap:4px}.tc-range,.tc-delivery{margin:0 21px;padding-left:0;padding-right:0}}
@media(prefers-reduced-motion:reduce){.telecom *{transition:none!important;animation:none!important}}
`;

export const extractedStyles = industryStyles + telecomStyles;
