import { CMS_CONTRACT_VERSION, type PlatformContent } from "./cms-content";

const governanceDefaults = {
  visibility: "public" as const,
  order: 0,
  sources: [],
  relatedIds: [],
};

export const cognibasePulseDraftContent = {
  schemaVersion: CMS_CONTRACT_VERSION,
  category: "Enterprise knowledge",
  summary: "CogniBase connects AI to your documents, databases and business systems, and returns grounded answers with the source cited. It runs in your cloud, on your premises, under your control.",
  template: "cognibase-pulse",
  pulsePage: {
    variant: "cognibase-pulse",
    layout: "editorial",
    tone: "evidence-led",
    hero: {
      eyebrow: "Products / CogniBase",
      headline: "Enterprise knowledge, answered with proof.",
      body: "CogniBase connects AI to your documents, databases and business systems, and returns grounded answers with the source cited. It runs in your cloud, on your premises, under your control.",
      ctas: [
        { label: "Book a demo", href: "/contact" },
        { label: "See how it works", href: "#how-it-works" },
      ],
      footnote: "Knowledge in. Evidence out.",
    },
    diagram: {
      accessibleDescription: "A question retrieves passages from controlled enterprise sources through hybrid search and reranking, producing an answer with source citations.",
      labels: [
        { id: "topBrand", text: "CogniBase / Evidence route" },
        { id: "topCaption", text: "Illustrative flow" },
        { id: "question", text: "What does the policy actually say?" },
        { id: "sourcePolicy", text: "Policy / PDF" },
        { id: "sourcePolicyDetail", text: "Page · passage" },
        { id: "sourceWiki", text: "Internal wiki" },
        { id: "sourceWikiDetail", text: "Section · article" },
        { id: "sourceRecords", text: "Records / SQL" },
        { id: "sourceRecordsDetail", text: "Record · source" },
        { id: "retrieval", text: "Retrieve & rerank" },
        { id: "keyword", text: "Keyword" },
        { id: "semantic", text: "Semantic" },
        { id: "relevantEvidence", text: "Relevant evidence" },
        { id: "answerTitle", text: "Grounded answer" },
        { id: "sourceLinked", text: "Source linked" },
        { id: "answer", text: "An answer you can trace back to the exact passage, page or record." },
        { id: "citationPolicy", text: "↗ Policy · page" },
        { id: "citationWiki", text: "↗ Wiki · section" },
        { id: "accessRights", text: "Access rights preserved" },
        { id: "noGuess", text: "Not in the data? No guess." },
      ],
    },
    proofItems: ["Cited answers", "Hybrid retrieval", "Self-hostable", "EU data residency", "Teams-native"],
    sections: [
      {
        id: "problem", visible: true, eyebrow: "The problem",
        heading: "A plausible answer is not enough.",
        body: "Most enterprise AI pilots stall for the same three reasons. Answers can't be traced back to a source, so nobody trusts them. The knowledge they need is scattered across SharePoint, ERP, CRM, wikis and databases. And data can't leave the building, which rules out most off-the-shelf tools.",
        items: [{ title: "CogniBase is built for exactly these constraints.", body: "CogniBase is built for exactly these constraints." }],
        links: [],
      },
      {
        id: "capabilities", visible: true, eyebrow: "Core capabilities",
        heading: "From scattered sources to defensible answers.",
        body: "Retrieval, integration, sovereignty and evaluation are designed as parts of the same knowledge system.",
        items: [
          { title: "Grounded answers with citations", body: "Every answer links back to the passage, page or record it came from. If the answer isn't in your data, CogniBase says so instead of guessing.", label: "Evidence, not inference" },
          { title: "Hybrid retrieval and reranking", body: "Keyword and semantic search run together, and a reranking stage then promotes the most relevant evidence. The result is higher precision on the questions that matter: policy details, part numbers, contract clauses.", label: "Find the right passage" },
          { title: "Documents and structured data in one place", body: "Ask questions across PDFs, Word files and wikis, and query databases in plain language through text-to-SQL. One interface covers both unstructured and structured knowledge.", label: "One knowledge surface" },
          { title: "Composable integration layer", body: "Connectors and adapters bring CogniBase into Microsoft Teams, web chat, internal portals and workflow tools, so AI shows up where work already happens instead of in yet another app.", label: "In the flow of work" },
          { title: "Sovereign by design", body: "You can deploy on your own infrastructure or in an EU cloud region, with open-weight models where required. Your data, embeddings, logs and prompts stay under your control.", label: "Your boundary" },
          { title: "Security and quality built in", body: "Prompt-injection hardening, role-based access to sources and full audit logs are standard. Built-in evaluation measures answer accuracy against golden question sets before and after every change.", label: "Measured continuously" },
        ],
        links: [],
      },
      {
        id: "how-it-works", visible: true, eyebrow: "How it works",
        heading: "A clear path from source to answer.",
        body: "Every step keeps the evidence and its boundaries in view.",
        items: [
          { title: "Connect", body: "Point CogniBase at your document stores, databases and systems.", label: "01 / 04" },
          { title: "Index", body: "Content is chunked, enriched with metadata and indexed for hybrid search, respecting existing access rights.", label: "02 / 04" },
          { title: "Ask", body: "Users ask questions in Teams, on the web or through an API.", label: "03 / 04" },
          { title: "Verify", body: "Answers arrive with citations, and quality is tracked continuously with evaluation reports.", label: "04 / 04" },
        ],
        footer: "The answer keeps its route back to the evidence.", links: [],
      },
      {
        id: "teams", visible: true, eyebrow: "Built for every team",
        heading: "One knowledge layer. Many ways to work.",
        body: "Different questions, same standard of traceability.",
        items: [
          { title: "Customer Support", body: "Resolve tickets faster with answers drawn from manuals, FAQs and past cases." },
          { title: "Legal & Compliance", body: "Search contracts and regulations with clause-level citations." },
          { title: "Finance", body: "Query policies and financial data in plain language, including via text-to-SQL." },
          { title: "People & HR", body: "Give employees instant, accurate answers on policies and benefits." },
          { title: "Operations", body: "Put procedures, SOPs and technical documentation at the fingertips of field and plant teams." },
          { title: "IT & Engineering", body: "Make runbooks, architecture decisions and internal docs searchable in one place." },
        ],
        links: [],
      },
      {
        id: "deployment", visible: true, eyebrow: "Deployment options",
        heading: "Your environment sets the boundary.",
        body: "Choose the operating model that fits your infrastructure and sovereignty requirements.",
        items: [
          { title: "Managed EU cloud", body: "Fastest start, hosted in European regions.", label: "01 / 03", detail: "Hosted in region" },
          { title: "Your cloud", body: "Deployed into your Azure, AWS or GCP tenant.", label: "02 / 03", detail: "Your tenant" },
          { title: "On-premises", body: "Fully air-gapped with open-weight models on your own hardware.", label: "03 / 03", detail: "Your hardware" },
        ],
        links: [],
      },
      {
        id: "trust", visible: true, eyebrow: "Trust and compliance",
        heading: "Control is part of the architecture.",
        body: "CogniBase is designed for regulated industries. It keeps data in the region you choose, gives you traceability for every answer, logs every query for audit, and uses architecture patterns that support GDPR and EU AI Act obligations.",
        items: [
          { title: "Data in the region you choose", body: "Data in the region you choose" },
          { title: "Traceability for every answer", body: "Traceability for every answer" },
          { title: "Every query logged for audit", body: "Every query logged for audit" },
        ],
        links: [],
      },
      {
        id: "faq", visible: true, eyebrow: "FAQ",
        heading: "The practical questions.",
        body: "The details that matter before you put knowledge into production.",
        items: [
          { title: "Which models does CogniBase use?", body: "Commercial or open-weight models, depending on your sovereignty and cost requirements. You choose, and you can switch." },
          { title: "Does it respect existing permissions?", body: "Yes. Users only retrieve content they are already allowed to see." },
          { title: "How long does a pilot take?", body: "A focused proof of concept on one knowledge domain typically runs in weeks, not months." },
          { title: "Can it take actions, not just answer questions?", body: "Yes. Through the integration layer, CogniBase can feed agentic workflows that act in your systems." },
        ],
        links: [],
      },
    ],
    sectionOrder: ["problem", "capabilities", "how-it-works", "teams", "deployment", "trust", "faq"],
    closing: {
      eyebrow: "Start with evidence",
      heading: "Put your enterprise knowledge to work.",
      body: "Start with one team and one knowledge domain, then measure the results.",
      cta: { label: "Book a demo", href: "/contact" },
      footerLeft: "CogniBase / Cognirise",
      footerRight: "Answers you can account for",
    },
  },
  sections: [],
  capabilities: [],
  differentiators: [],
  ...governanceDefaults,
} satisfies PlatformContent;

export const cogniagentsPulseDraftContent = {
  schemaVersion: CMS_CONTRACT_VERSION,
  category: "Agentic workflows",
  summary: "CogniAgents are ready-made AI workflows for finance, operations, customer service, sales, HR and IT. Each comes with proven best practices built in and is tailored to how your company actually works.",
  template: "cogniagents-pulse",
  pulsePage: {
    variant: "cogniagents-pulse",
    layout: "editorial",
    tone: "operational",
    hero: {
      eyebrow: "Products / CogniAgents",
      headline: "Agentic workflows for every business function.",
      body: "CogniAgents are ready-made AI workflows for finance, operations, customer service, sales, HR and IT. Each comes with proven best practices built in and is tailored to how your company actually works.",
      ctas: [
        { label: "Explore the agents", href: "#agents-by-function" },
        { label: "Book a workshop", href: "/contact" },
      ],
      footnote: "A proven starting point. Your operating rules.",
    },
    diagram: {
      accessibleDescription: "Illustrative workflow: a defined process receives a case, the agent prepares a recommendation using grounded knowledge, a person reviews at an approval checkpoint, and an approved action is carried out within permissions.",
      labels: [
        { id: "topBrand", text: "CogniAgents / Work route" },
        { id: "topCaption", text: "Illustrative flow" },
        { id: "title", text: "The work moves forward. The decision stays visible." },
        { id: "intakeStep", text: "01 / Intake" },
        { id: "intake", text: "Work enters a defined process" },
        { id: "prepareStep", text: "02 / Prepare" },
        { id: "prepare", text: "Agent checks context and rules" },
        { id: "humanCheckpoint", text: "Human checkpoint" },
        { id: "humanReview", text: "Review · approve · override" },
        { id: "actStep", text: "03 / Act" },
        { id: "act", text: "Approved action in your systems" },
        { id: "permissions", text: "Permissions define the boundary" },
        { id: "decisionLogged", text: "Decision logged" },
      ],
    },
    proofItems: ["Function-specific", "Best practices built in", "Human-in-the-loop", "Runs on CogniBase", "Sovereign deployment"],
    sections: [
      {
        id: "problem", visible: true, eyebrow: "The problem",
        heading: "An answer is not finished work.",
        body: "Generic AI assistants answer questions, but they don't finish the work. Building agents from scratch takes months, and every team reinvents the same processes. Many pilots automate a broken process instead of a good one, and agents that act without oversight are a risk no compliance team will sign off on.",
        items: [{ title: "CogniAgents start from a proven way of running each function, then adapt it to yours.", body: "CogniAgents start from a proven way of running each function, then adapt it to yours." }],
        links: [],
      },
      {
        id: "differences", visible: true, eyebrow: "What makes CogniAgents different",
        heading: "A better process, already in motion.",
        body: "Start with how the work should run. Then configure the boundaries, knowledge and actions around your organisation.",
        items: [
          { title: "Best practices, pre-built", body: "Each agent encodes how leading organisations run that function: the steps, the checks, the approvals and the KPIs. You start from a mature process, not a blank canvas.", label: "Start with a process" },
          { title: "Tailored to your business", body: "Workflows, rules, approval thresholds, tone and terminology are configured to your policies. Agents adapt to your process instead of forcing you into theirs.", label: "Make it yours" },
          { title: "Agents that act, not just answer", body: "CogniAgents read, decide and take action in your systems: they create tickets, update records, draft documents, route cases and trigger follow-ups.", label: "Finish the work" },
          { title: "Human in the loop, by design", body: "You define exactly where people review, approve or override. Every decision is logged with its reasoning and the sources it used.", label: "Keep people in control" },
          { title: "Grounded in your knowledge", body: "Built on CogniBase, every agent works from your own documents, data and systems, with citations, so outcomes are explainable and auditable.", label: "Know the source" },
          { title: "Sovereign and secure", body: "Agents can be deployed in an EU cloud, in your own tenant or on premises, with open-weight models where required. Role-based permissions limit what each agent can see and do.", label: "Define the boundary" },
        ],
        links: [],
      },
      {
        id: "functions", visible: true, eyebrow: "Agents by function",
        heading: "The work is specific. So are the agents.",
        body: "One starting point per function, configured for the workflows, policies and systems your team actually uses.",
        items: [
          { title: "Finance", body: "Invoice intake and coding, three-way matching, expense review, collections follow-up, month-end close support and variance commentary.", label: "01 / Business operations" },
          { title: "Customer Service", body: "Ticket triage and routing, grounded answer drafting, case summarisation, escalation handling and quality review of resolved cases.", label: "01 / Business operations" },
          { title: "Sales", body: "Lead qualification, account research, personalised outreach drafting, CRM hygiene and conversational sales agents on web, WhatsApp and Telegram.", label: "01 / Business operations" },
          { title: "Insurance & Claims", body: "First notice of loss intake, document checks, claim triage, fraud signals and handler assistance across the claim file.", label: "02 / Specialist workflows" },
          { title: "Operations & Manufacturing", body: "Predictive maintenance alerts, anomaly detection, SOP guidance for field and plant teams, and BOM-to-QA checks.", label: "02 / Specialist workflows" },
          { title: "IT & Network Operations", body: "Incident triage, runbook execution, change-request drafting and network monitoring agents inside Microsoft Teams.", label: "02 / Specialist workflows" },
          { title: "People & HR", body: "Policy Q&A, onboarding workflows, candidate screening against defined criteria and HR case handling.", label: "03 / People & governance" },
          { title: "Risk & Compliance", body: "AML alert triage, KYC document review, regulatory change monitoring and audit evidence collection.", label: "03 / People & governance" },
          { title: "Project & Portfolio Management", body: "Status reporting, risk and dependency tracking, meeting follow-ups and portfolio health summaries.", label: "03 / People & governance" },
        ],
        links: [],
      },
      {
        id: "how-it-works", visible: true, eyebrow: "How it works",
        heading: "Start narrow. Earn the right to scale.",
        body: "Every stage has a purpose: define the work, fit the agent to your rules, measure it under review, then expand what has been proven.",
        items: [
          { title: "Discover", body: "In a short workshop, we map the function, its current process and the outcome it needs.", label: "01 / 04", detail: "A process worth improving" },
          { title: "Configure", body: "We start from the best-practice agent and tailor its rules, approvals, systems and language to your organisation.", label: "02 / 04", detail: "Your rules, in the workflow" },
          { title: "Pilot", body: "The agent runs on a defined scope with human review, measured against agreed KPIs.", label: "03 / 04", detail: "Evidence before rollout" },
          { title: "Scale", body: "Proven agents are rolled out across teams, and new functions are added from the same foundation.", label: "04 / 04", detail: "More functions, one foundation" },
        ],
        links: [],
      },
      {
        id: "foundation", visible: true, eyebrow: "Built on CogniBase",
        heading: "One foundation. More work done.",
        body: "Every CogniAgent draws on CogniBase for grounded knowledge, system integration and audit logging. Your first agent sets up the foundation, and every agent after it deploys faster.",
        items: [
          { title: "Function-specific workflow", body: "Function-specific workflow" },
          { title: "Configured approvals", body: "Configured approvals" },
          { title: "Actions within permissions", body: "Actions within permissions" },
          { title: "Shared foundation / illustrative", body: "Shared foundation / illustrative" },
          { title: "CogniBase", body: "CogniBase", label: "Shared foundation" },
          { title: "Grounded knowledge", body: "Grounded knowledge" },
          { title: "System integration", body: "System integration" },
          { title: "Audit logging", body: "Audit logging" },
        ],
        links: [{ label: "Explore CogniBase", href: "/platforms/cognibase" }],
      },
      {
        id: "deployment", visible: true, eyebrow: "Deployment options",
        heading: "Deploy within your boundary.",
        body: "Choose the environment that fits your infrastructure and sovereignty requirements.",
        items: [
          { title: "Managed EU cloud", body: "Fastest start, hosted in European regions.", label: "01 / 03", detail: "European region" },
          { title: "Your cloud", body: "Deployed into your own cloud tenant.", label: "02 / 03", detail: "Your tenant" },
          { title: "On-premises", body: "Fully isolated, with open-weight models on your own hardware.", label: "03 / 03", detail: "Your hardware" },
        ],
        links: [],
      },
      {
        id: "faq", visible: true, eyebrow: "FAQ",
        heading: "Questions, answered.",
        body: "The questions an operations and compliance team should ask before an agent takes on real work.",
        items: [
          { title: "Are these off-the-shelf or custom?", body: "Both. Each agent starts from a best-practice template and is then tailored to your processes, systems and policies." },
          { title: "Can agents take action in our systems?", body: "Yes, through CogniBase's integration layer, and always within permissions and approval rules you define." },
          { title: "How do we keep control?", body: "Human checkpoints, role-based permissions and full decision logs are built into every workflow." },
          { title: "How quickly can we start?", body: "A single-function pilot typically runs in weeks, starting with one process and clear KPIs." },
          { title: "Do you support the EU AI Act?", body: "CogniAgents are designed with transparency, human oversight and logging, which support obligations under the EU AI Act." },
        ],
        links: [],
      },
    ],
    sectionOrder: ["problem", "differences", "functions", "how-it-works", "foundation", "deployment", "faq"],
    closing: {
      eyebrow: "Make the first move",
      heading: "Start with one function. Prove it. Then scale.",
      body: "Pick the process that costs your team the most time, and we'll show you what an agent can do with it.",
      cta: { label: "Book a workshop", href: "/contact" },
      footerLeft: "CogniAgents / Function-specific AI workflows",
      footerRight: "Human oversight, built in",
    },
  },
  sections: [],
  capabilities: [],
  differentiators: [],
  ...governanceDefaults,
} satisfies PlatformContent;

export const cognibasePulsePageDraft = cognibasePulseDraftContent.pulsePage;
export const cogniagentsPulsePageDraft = cogniagentsPulseDraftContent.pulsePage;