import type { Step } from "./types";

/** The four steps, used on Home (strip) and How we work (full). */
export const STEPS: Step[] = [
  {
    id: 1,
    name: "Innovate",
    time: "1 day",
    summary: "We agree the one process worth proving and what success looks like.",
    weDo: "We map the process, the people it affects and the decision it must support. We agree what the prototype has to prove.",
    youDo: "Bring the process, its owner and the people who decide.",
    youHave: "A chosen process, a named owner and a clear test for the prototype.",
    accent: "#7659df",
    image: "/images/cognirise/blueprint-innovate.jpg",
    imageAlt: "A client team and Cognirise choosing the process to prove, around a workshop table.",
    imagePosition: "50% 48%",
  },
  {
    id: 2,
    name: "Demonstrate",
    time: "48 hours",
    summary: "You test a working prototype and decide: go on, change course, or stop.",
    weDo: "We build a prototype of the key journey on representative data.",
    youDo: "Test it. Challenge it. Decide: go on, change course, or stop.",
    youHave: "A working prototype and a recorded decision.",
    accent: "#db509e",
    image: "/images/cognirise/blueprint-demonstrate.jpg",
    imageAlt: "A client team testing a working prototype on a large tablet.",
    imagePosition: "50% 45%",
  },
  {
    id: 3,
    name: "Activate",
    time: "2 to 4 weeks",
    summary: "We build the working system with your team, with the controls to run it.",
    weDo: "We build the working system with your team, connect it to your platforms and put the controls in place.",
    youDo: "Give product decisions, access to your experts and sign-off at agreed points.",
    youHave: "A system your people can use, with the controls to run it.",
    accent: "#e74f91",
    image: "/images/cognirise/blueprint-activate.jpg",
    imageAlt: "Engineers and client staff building the working system together.",
    imagePosition: "50% 52%",
  },
  {
    id: 4,
    name: "Operate",
    time: "4 to 12 weeks",
    summary: "Your team runs it. We hand over the code, the knowledge and the plan to grow it.",
    weDo: "We harden it, set up monitoring and hand over the code and the knowledge.",
    youDo: "Name the operational owners and accept the system against agreed evidence.",
    youHave: "A system your team runs, owns and can extend.",
    accent: "#ff775d",
    image: "/images/cognirise/blueprint-operate.jpg",
    imageAlt: "A client operations team running the system from their own control room.",
    imagePosition: "50% 48%",
  },
];
