// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cognios-authority-atlas/AuthorityAtlas.tsx": () => import("../components/mockups/cognios-authority-atlas/AuthorityAtlas.tsx"),
  "./components/mockups/cognios-kernel-stack/ExplodedKernelStack.tsx": () => import("../components/mockups/cognios-kernel-stack/ExplodedKernelStack.tsx"),
  "./components/mockups/cognirise-directions/AgenticSurge.tsx": () => import("../components/mockups/cognirise-directions/AgenticSurge.tsx"),
  "./components/mockups/cognirise-directions/CognirisePulse.tsx": () => import("../components/mockups/cognirise-directions/CognirisePulse.tsx"),
  "./components/mockups/cognirise-directions/CognirisePulseLibrary.tsx": () => import("../components/mockups/cognirise-directions/CognirisePulseLibrary.tsx"),
  "./components/mockups/cognirise-directions/ExecutiveFieldManual.tsx": () => import("../components/mockups/cognirise-directions/ExecutiveFieldManual.tsx"),
  "./components/mockups/cognirise-directions/GradientEngine.tsx": () => import("../components/mockups/cognirise-directions/GradientEngine.tsx"),
  "./components/mockups/cognirise-directions/LivingArchitecture.tsx": () => import("../components/mockups/cognirise-directions/LivingArchitecture.tsx"),
  "./components/mockups/cognirise-directions/PrecisionInMotion.tsx": () => import("../components/mockups/cognirise-directions/PrecisionInMotion.tsx"),
  "./components/mockups/cognirise-directions/VisibleIntelligence.tsx": () => import("../components/mockups/cognirise-directions/VisibleIntelligence.tsx"),
  "./components/mockups/cognirise-site/AboutPeople.tsx": () => import("../components/mockups/cognirise-site/AboutPeople.tsx"),
  "./components/mockups/cognirise-site/AgenticTransformation.tsx": () => import("../components/mockups/cognirise-site/AgenticTransformation.tsx"),
  "./components/mockups/cognirise-site/CogniOSPlatform.tsx": () => import("../components/mockups/cognirise-site/CogniOSPlatform.tsx"),
  "./components/mockups/cognirise-site/IndustriesOverview.tsx": () => import("../components/mockups/cognirise-site/IndustriesOverview.tsx"),
  "./components/mockups/cognirise-site/InsightsEditorial.tsx": () => import("../components/mockups/cognirise-site/InsightsEditorial.tsx"),
  "./components/mockups/cognirise-site/PublicSector.tsx": () => import("../components/mockups/cognirise-site/PublicSector.tsx"),
  "./components/mockups/cognirise-site/ServicesOverview.tsx": () => import("../components/mockups/cognirise-site/ServicesOverview.tsx"),
  "./components/mockups/cognirise-site/ValueScan.tsx": () => import("../components/mockups/cognirise-site/ValueScan.tsx"),
  "./components/mockups/cognirise-site/WorkProof.tsx": () => import("../components/mockups/cognirise-site/WorkProof.tsx")
};
