const base=import.meta.env.BASE_URL;
export default function Journey(){return <div className="w-screen h-screen overflow-hidden relative bg-[#f8f7f4] text-text font-body px-[5vw] py-[5vh]">
<div className="flex justify-between items-center"><p className="text-[1.5vw] tracking-[.13em] font-semibold">DELIVERY / 05</p><img src={base+"images/logo-blue.svg"} crossOrigin="anonymous" alt="Cognirise" className="w-[10vw]"/></div>
<h1 className="font-display text-[5.2vw] leading-[.98] tracking-[-.075em] mt-[5vh]">Stay with the <span className="text-accent">work.</span></h1>
<div className="relative mt-[9vh]"><div className="absolute top-[3.4vh] left-[2vw] right-[2vw] h-[1vh] bg-[linear-gradient(90deg,#7659df,#db509e,#ff775d)]"/>
<div className="grid grid-cols-5 gap-[1.6vw] relative">
<div><div className="w-[4.3vw] h-[4.3vw] rounded-full bg-primary text-white grid place-items-center text-[1.8vw] font-bold">01</div><h2 className="font-display text-[2.5vw] mt-[4vh]">Diagnose</h2><p className="text-[2vw] leading-[1.3] mt-[2vh]">find the process where pressure and value collide</p></div>
<div><div className="w-[4.3vw] h-[4.3vw] rounded-full bg-primary text-white grid place-items-center text-[1.8vw] font-bold">02</div><h2 className="font-display text-[2.5vw] mt-[4vh]">Design</h2><p className="text-[2vw] leading-[1.3] mt-[2vh]">rebuild the workflow around intelligence</p></div>
<div><div className="w-[4.3vw] h-[4.3vw] rounded-full bg-primary text-white grid place-items-center text-[1.8vw] font-bold">03</div><h2 className="font-display text-[2.5vw] mt-[4vh]">Build</h2><p className="text-[2vw] leading-[1.3] mt-[2vh]">connect data, controls and enterprise systems</p></div>
<div><div className="w-[4.3vw] h-[4.3vw] rounded-full bg-primary text-white grid place-items-center text-[1.8vw] font-bold">04</div><h2 className="font-display text-[2.5vw] mt-[4vh]">Deploy</h2><p className="text-[2vw] leading-[1.3] mt-[2vh]">move into governed production</p></div>
<div><div className="w-[4.3vw] h-[4.3vw] rounded-full bg-accent text-white grid place-items-center text-[1.8vw] font-bold">05</div><h2 className="font-display text-[2.5vw] mt-[4vh]">Compound</h2><p className="text-[2vw] leading-[1.3] mt-[2vh]">grow capability after the first release</p></div></div></div></div>}