const base=import.meta.env.BASE_URL;
export default function OperatingSystem(){return <div className="w-screen h-screen overflow-hidden relative bg-bg text-text font-body px-[5vw] py-[5vh]">
<div className="flex justify-between items-center"><p className="text-[calc(1.5*var(--slide-vw))] tracking-[.13em] font-semibold">COGNIOS / 07</p><img src={base+"images/logo-blue.svg"} crossOrigin="anonymous" alt="Cognirise" className="w-[10vw]"/></div>
<h1 className="font-display text-[calc(4.9*var(--slide-vw))] tracking-[-.075em] leading-[.98] mt-[4vh] w-[78vw]">The operating system for <span className="text-accent">governed intelligence.</span></h1>
<div className="mt-[5vh] grid grid-cols-[1fr_2.5fr] gap-[3vw]"><div className="pt-[3vh] border-t border-primary"><p className="text-[calc(1.8*var(--slide-vw))] leading-[1.45]">Six layers connect people, agents, knowledge and enterprise systems.</p></div><div className="space-y-[1vh]">
<div className="grid grid-cols-[1.2fr_2fr] bg-primary text-white px-[2vw] py-[1.2vh]"><b className="text-[calc(2*var(--slide-vw))]">Experience</b><span className="text-[calc(2*var(--slide-vw))]">one front door for people and channels</span></div>
<div className="grid grid-cols-[1.2fr_2fr] bg-[#253f6b] text-white px-[2vw] py-[1.2vh]"><b className="text-[calc(2*var(--slide-vw))]">Intelligence</b><span className="text-[calc(2*var(--slide-vw))]">governed agents and decision support</span></div>
<div className="grid grid-cols-[1.2fr_2fr] bg-[#40587e] text-white px-[2vw] py-[1.2vh]"><b className="text-[calc(2*var(--slide-vw))]">Process</b><span className="text-[calc(2*var(--slide-vw))]">orchestration, authority and exception handling</span></div>
<div className="grid grid-cols-[1.2fr_2fr] bg-[#e6dfef] px-[2vw] py-[1.2vh]"><b className="text-[calc(2*var(--slide-vw))]">Knowledge</b><span className="text-[calc(2*var(--slide-vw))]">grounded organisational context</span></div>
<div className="grid grid-cols-[1.2fr_2fr] bg-[#f1d7e5] px-[2vw] py-[1.2vh]"><b className="text-[calc(2*var(--slide-vw))]">Integration</b><span className="text-[calc(2*var(--slide-vw))]">enterprise systems and deterministic execution</span></div>
<div className="grid grid-cols-[1.2fr_2fr] bg-[#ffd8cf] px-[2vw] py-[1.2vh]"><b className="text-[calc(2*var(--slide-vw))]">Foundation</b><span className="text-[calc(2*var(--slide-vw))]">identity, security, audit and memory</span></div></div></div></div>}