const base=import.meta.env.BASE_URL;
export default function ValueChain(){return <div className="w-screen h-screen overflow-hidden relative bg-bg text-text font-body px-[5vw] py-[5vh]">
<header className="flex justify-between items-center"><p className="text-[calc(1.5*var(--slide-vw))] font-semibold tracking-[.13em]">VALUE CHAIN / 21</p><img src={base+"images/logo-blue.svg"} crossOrigin="anonymous" alt="Cognirise" className="w-[10vw]"/></header>
<h1 className="font-display text-[calc(4.4*var(--slide-vw))] tracking-[-.06em] mt-[3vh]">Find value where <span className="text-accent">work changes hands.</span></h1>
<div className="mt-[5vh] grid grid-cols-5 border-y-[.15vw] border-primary">
<section className="h-[34vh] p-[1.6vw] border-r border-[#cbd3e1]"><b className="text-[calc(1.5*var(--slide-vw))] text-accent">01</b><h2 className="font-display text-[calc(2.3*var(--slide-vw))] mt-[2vh]">Sense</h2><p className="text-[calc(1.5*var(--slide-vw))] text-muted mt-[2vh]">Signals arrive from customers and operations</p></section>
<section className="h-[34vh] p-[1.6vw] border-r border-[#cbd3e1]"><b className="text-[calc(1.5*var(--slide-vw))] text-accent">02</b><h2 className="font-display text-[calc(2.3*var(--slide-vw))] mt-[2vh]">Decide</h2><p className="text-[calc(1.5*var(--slide-vw))] text-muted mt-[2vh]">Experts interpret context and select a path</p></section>
<section className="h-[34vh] p-[1.6vw] border-r border-[#cbd3e1] bg-primary text-white"><b className="text-[calc(1.5*var(--slide-vw))] text-[#f59ac9]">03 / CONSTRAINT</b><h2 className="font-display text-[calc(2.3*var(--slide-vw))] mt-[2vh]">Coordinate</h2><p className="text-[calc(1.5*var(--slide-vw))] text-[#dce4f0] mt-[2vh]">Queues, re-keying and approvals slow flow</p></section>
<section className="h-[34vh] p-[1.6vw] border-r border-[#cbd3e1]"><b className="text-[calc(1.5*var(--slide-vw))] text-accent">04</b><h2 className="font-display text-[calc(2.3*var(--slide-vw))] mt-[2vh]">Execute</h2><p className="text-[calc(1.5*var(--slide-vw))] text-muted mt-[2vh]">Teams and agents complete governed work</p></section>
<section className="h-[34vh] p-[1.6vw]"><b className="text-[calc(1.5*var(--slide-vw))] text-accent">05</b><h2 className="font-display text-[calc(2.3*var(--slide-vw))] mt-[2vh]">Learn</h2><p className="text-[calc(1.5*var(--slide-vw))] text-muted mt-[2vh]">Outcomes improve the next decision</p></section></div>
<p className="text-[calc(2*var(--slide-vw))] mt-[4vh]"><b>Action:</b> instrument the coordination step first—it holds the largest recoverable delay.</p></div>}