/**
 * Financial Services specialist editorial content.
 *
 * This module deliberately does not mutate the shared INDUSTRIES collection.
 * The CMS successor imports `bankingPov` into Financial Services only
 * after its immutable media selections have passed review.
 */
import type { BankingPov } from "@workspace/api-zod";

const bankingMedia = {
  coreBanking: {
    mediaId: "c0b9910c-6905-4517-973e-fbb4b9928981",
    mediaVersionId: "30e85256-3060-45dc-a82a-49c08c3ed55f",
    role: "supporting" as const,
    altText: "A modern banking gateway with flowing illuminated paths, representing governed core operations.",
  },
  contactCentre: {
    mediaId: "8cb223cb-fe02-41a6-9ba4-1f8ee3fb0c6b",
    mediaVersionId: "1f0a22a8-68b9-4788-822f-ee4d9fb6b68a",
    role: "supporting" as const,
    altText: "Abstract illuminated forms in dialogue, representing human and AI collaboration in a contact centre.",
  },
  softwareDelivery: {
    mediaId: "f5e20ba7-405c-4da7-b411-332fb63ff40f",
    mediaVersionId: "9b0b1961-fabe-477a-a704-315019c79156",
    role: "supporting" as const,
    altText: "Directed illuminated pathways through a digital structure, representing governed software delivery.",
  },
  marketingIntelligence: {
    mediaId: "20b29151-e8e7-4a10-99ea-dd8c79ab6004",
    mediaVersionId: "8c11c77b-84ba-4de8-9bdf-36f7a82cb218",
    role: "supporting" as const,
    altText: "A luminous knowledge field with connected signals, representing governed marketing intelligence.",
  },
  productionReadiness: {
    mediaId: "54410f6e-b8d3-4dfb-8504-b0a15fc69b14",
    mediaVersionId: "72dc59fb-9c8a-4735-8e15-bc56ede3fc92",
    role: "supporting" as const,
    altText: "Violet and coral light flows pass through transparent gates beside a metallic vault-like structure.",
  },
};

export const bankingPov: BankingPov = {
  version: 1,
  market: "uae",
  descriptor: "Banking AI, from employee capacity to accountable enterprise workflows",
  hero: {
    eyebrow: "Banking & financial services",
    heading: "One bank. Three levels of AI value.",
    body: "Create capacity, improve customer outcomes and redesign banking workflows—from individual assistants to coordinated agents, with human accountability built in.",
    startingPointsAnchorLabel: "Explore four practical starting points",
    selectedWorkAnchorLabel: "See selected work",
  },
  evidenceSignals: [
    {
      statement: "In the Bank of England and FCA’s 2024 survey, 75% of responding UK financial-services firms said they were using AI; only 2% of reported use cases had fully autonomous decision-making.",
      qualification: "UK survey findings, not a UAE or global adoption estimate. The use-case figure describes reported autonomy, not a recommendation for unrestricted autonomy.",
      url: "https://www.bankofengland.co.uk/report/2024/artificial-intelligence-in-uk-financial-services-2024",
      label: "Artificial intelligence in UK financial services – 2024",
      publisher: "Bank of England and Financial Conduct Authority",
      publicationPeriod: "21 November 2024",
      accessedAt: "2026-09-11",
      jurisdiction: "UK",
      kind: "Official source",
    },
    {
      statement: "DBS reports that its data analytics and AI/ML initiatives included over 2,000 models and more than 430 use cases, with approximately SGD 1 billion in economic value in 2025.",
      qualification: "Company-reported DBS figure. It is not independently validated, is not limited to generative or agentic AI, and is not a Cognirise client result or a portable ROI promise.",
      url: "https://www.dbs.com/annualreports/2025/ceo-reflections.html",
      label: "Annual Report 2025: CEO reflections",
      publisher: "DBS Bank",
      publicationPeriod: "Annual Report 2025",
      accessedAt: "2026-09-11",
      jurisdiction: "Singapore",
      kind: "Company-reported",
    },
    {
      statement: "CBUAE guidance for UAE licensed financial institutions addresses responsible AI and ML use in consumer-relevant areas, including governance and accountability, fairness, transparency and explainability, and data quality, privacy and security.",
      qualification: "Guidance, not a certification, product approval or assurance that a deployment complies. It should be read with relevant CBUAE regulations and Model Management Standards.",
      url: "https://rulebook.centralbank.ae/en/rulebook/guidance-note-consumer-protection-and-responsible-adoption-and-use-artificial-intelligence",
      label: "Guidance Note on the Consumer Protection and Responsible Adoption and Use of Artificial Intelligence and Machine Learning by Licensed Financial Institutions in the U.A.E.",
      publisher: "Central Bank of the UAE",
      publicationPeriod: "Issued 11 February 2026",
      accessedAt: "2026-09-11",
      jurisdiction: "United Arab Emirates",
      kind: "Official source",
    },
    {
      statement: "The FSB consultation proposes a menu of 12 sound practices for organisation-wide AI governance and management across the AI lifecycle.",
      qualification: "Consultation report, not binding regulation or a final international standard.",
      url: "https://www.fsb.org/2026/06/sound-practices-for-responsible-adoption-of-artificial-intelligence-ai-consultation-report",
      label: "Sound Practices for Responsible Adoption of Artificial Intelligence: Consultation report",
      publisher: "Financial Stability Board",
      publicationPeriod: "10 June 2026",
      accessedAt: "2026-09-11",
      jurisdiction: "International",
      kind: "Official source",
    },
  ],
  valueOutcomes: [
    {
      title: "Capacity for higher-value work",
      body: "Remove repetitive reading, drafting, searching and routing from the work that bankers, operations teams and engineers must still own.",
      measures: ["Time returned to customer or judgement work", "Exception volume and resolution time", "Adoption by the accountable team"],
    },
    {
      title: "Customer outcomes that hold up",
      body: "Design service and sales journeys around resolved need, clear communication and informed escalation—not containment alone.",
      measures: ["Resolution and repeat-contact rate", "Customer experience and escalation quality", "Conversion or retention with suitable-treatment checks"],
    },
    {
      title: "Speed with visible control",
      body: "Make workflow speed, policy adherence and evidence available together, so a faster path never conceals a weaker decision.",
      measures: ["Cycle time and straight-through rate", "Manual fixes and control exceptions", "Decision evidence, approvals and audit completeness"],
    },
  ],
  adoptionLevels: [
    {
      level: 1,
      title: "Individual Assistants",
      value: "Give each employee a useful, governed assistant for the work around the decision.",
      illustrativeWork: ["Draft and summarise approved material", "Search current policy and product knowledge", "Prepare relationship-manager meeting briefs"],
      owner: "Business owner with information, risk and technology counterparts",
      readiness: ["Approved knowledge sources", "Role-based access", "Usage guidance and feedback loop"],
      measures: ["Time spent finding, preparing and drafting", "Source-grounding quality", "User adoption and override reasons"],
      decisionBoundary: "The assistant prepares and retrieves; the accountable employee remains responsible for judgement, advice and action.",
    },
    {
      level: 2,
      title: "Agentic Functions",
      value: "Redesign a bounded domain workflow so systems complete permitted steps and people focus on exceptions.",
      illustrativeWork: ["Credit-file and collateral preparation", "Onboarding, verification and reconciliation queues", "Policy-aware servicing and regulatory-change triage"],
      owner: "Named process owner, with risk/control owner and technology delivery owner",
      readiness: ["Mapped process and exception paths", "Reliable source systems and integration contracts", "Evaluation set, permissions and human gates"],
      measures: ["Cycle time by clean path and exception", "Straight-through completion and rework", "Gate outcomes, escalations and quality"],
      decisionBoundary: "An agent may act only within named permissions, limits and evidence requirements; it escalates ambiguity, threshold breaches and consequential judgement.",
    },
    {
      level: 3,
      title: "Agentic Enterprise",
      value: "Coordinate proven domain workflows across hand-offs while keeping operating authority explicit.",
      illustrativeWork: ["Cross-process exception orchestration", "Coordinated customer servicing across channels", "Portfolio and operations signals routed to accountable teams"],
      owner: "Executive sponsor, accountable operating owner and control-function leadership",
      readiness: ["Proven domain evaluations", "Shared identity, observability and audit design", "Operating model for incident response and change control"],
      measures: ["End-to-end outcome and customer effort", "Cross-domain exception and fallback rate", "Control performance, resilience and realised operating value"],
      decisionBoundary: "This is not unrestricted autonomy or a required destination for every workflow. Production authority is earned through evaluation, explicit permissions and measured operating results.",
    },
  ],
  valueDomains: [
    {
      id: "credit-lending",
      title: "Credit & Lending",
      purpose: "Move evidence gathering and policy preparation out of the analyst’s path while retaining accountable credit judgement.",
      examples: ["Relationship-manager meeting preparation and client briefs", "Credit-file and collateral summarisation", "Policy pre-screening and risk tiering"],
      measures: ["Preparation and decision cycle time, separately", "Exceptions, overrides and evidence completeness", "Portfolio and customer outcome measures"],
    },
    {
      id: "risk-fraud",
      title: "Risk & Fraud",
      purpose: "Prioritise the signals that merit investigation instead of expanding the alert queue.",
      examples: ["Transaction anomaly detection", "AML alert pre-screening and prioritisation", "Portfolio stress analysis on demand"],
      measures: ["Alert precision and investigation time", "Escalation quality and false-positive cost", "Loss, exposure and control outcomes"],
    },
    {
      id: "operations-process",
      title: "Operations & Process",
      purpose: "Create cleaner straight-through paths while making exceptions visible to the people who resolve them.",
      examples: ["Onboarding and document verification", "Workflow-engine processing", "Reconciliation and reporting preparation"],
      measures: ["Straight-through rate", "Manual fixes and queue age", "Completion quality and exception turnaround"],
    },
    {
      id: "customer-sales",
      title: "Customer & Sales",
      purpose: "Give customers and bankers relevant, permitted support at the moment of need.",
      examples: ["Voice and chat servicing", "Next-best-action recommendations", "Churn signals and retention offers"],
      measures: ["Resolution and customer effort", "Conversion, retention and suitability checks", "Escalation and repeat-contact rate"],
    },
    {
      id: "engineering-it",
      title: "Engineering & IT",
      purpose: "Increase delivery capacity with outputs that can be reviewed, tested and secured in the bank’s engineering system.",
      examples: ["Coding assistance", "Test and regression generation", "Legacy-code analysis and modernisation support"],
      measures: ["Lead time alongside defects and security findings", "Test coverage and review rework", "Developer experience and release reliability"],
    },
    {
      id: "compliance-regulation",
      title: "Compliance & Regulation",
      purpose: "Make policy and regulatory work easier to locate, interpret and evidence without transferring accountability.",
      examples: ["Regulation and internal-policy search", "Circular and rule-change impact analysis", "KYC and regulatory-reporting preparation"],
      measures: ["Research and impact-assessment cycle time", "Source coverage and traceability", "Review findings, exceptions and remediation time"],
    },
  ],
  startingPoints: [
    {
      id: "core-banking-operations",
      title: "Core Banking Operations",
      valueProposition: "Turn a rule-bound, exception-heavy process into a faster, traceable work queue.",
      problem: "Credit preparation and operational servicing often require people to assemble evidence across documents, policy and core systems before they can apply judgement.",
      cogniriseRole: "Cognirise maps the workflow, designs the evidence and exception model, integrates approved sources and evaluates bounded automation with accountable owners.",
      requiredInputs: ["Named workflow and exception taxonomy", "Current policy, product and source-system access", "Process owner, risk/control owner and baseline measures"],
      firstDeliverable: "A scoped clean-path and exception workflow with evidence views, explicit approval gates and a pilot scorecard.",
      measures: ["Credit preparation and decision cycle time, separately", "Exception rate and ageing", "Evidence completeness, overrides and rework"],
      decisionBoundary: "Credit decisions, material exceptions and policy interpretation remain with authorised people; the workflow can prepare, route and evidence only what its permissions allow.",
      action: { label: "Identify an operations workflow", href: "/value-scan" },
      image: bankingMedia.coreBanking,
      focalPoint: { x: 52, y: 50 },
    },
    {
      id: "contact-centre",
      title: "Contact Centre",
      valueProposition: "Design voice and service journeys that resolve the need while keeping identity, authority and escalation explicit.",
      problem: "High-volume calls can leave customers repeating context, while agents navigate identity checks, product rules and multiple servicing systems under time pressure.",
      cogniriseRole: "Cognirise redesigns the journey, integrates identity and servicing systems, specifies permitted actions and makes operational and control measures visible.",
      requiredInputs: ["Priority call reasons and current journey data", "Identity, consent, action and escalation rules", "Knowledge sources, system interfaces and service owners"],
      firstDeliverable: "A bounded journey specification and evaluated pilot for one call type, including transcript, escalation and action controls.",
      measures: ["Resolution, handling time and repeat contact", "Escalation quality and customer experience", "Containment only alongside suitable-resolution checks"],
      decisionBoundary: "The voice agent may answer or act only after the required verification and explicit authorisation; payments, account changes, limits and exceptions stay within configured permissions and human escalation.",
      action: { label: "Scope a service journey", href: "/value-scan" },
      image: bankingMedia.contactCentre,
      focalPoint: { x: 50, y: 48 },
    },
    {
      id: "software-delivery",
      title: "Software Delivery",
      valueProposition: "Use AI where engineering output can be inspected, tested and secured inside the bank’s delivery controls.",
      problem: "Requirements, documentation, regression work and legacy understanding can consume delivery capacity before teams reach the change that matters.",
      cogniriseRole: "Cognirise selects verifiable engineering workflows, integrates tools into existing delivery controls and establishes evaluation, review and secure-development practices.",
      requiredInputs: ["Delivery baseline and priority repositories", "Approved development environment and security controls", "Engineering owner, quality owner and release criteria"],
      firstDeliverable: "An evaluated engineering-assistance workflow for one product area, with review checkpoints and a lead-time, quality and security scorecard.",
      measures: ["Lead time alongside defect and security findings", "Review effort and test coverage", "Release reliability and developer feedback"],
      decisionBoundary: "Generated output is never self-approving: engineers retain code review, test, security and release authority.",
      action: { label: "Assess a delivery workflow", href: "/value-scan" },
      image: bankingMedia.softwareDelivery,
      focalPoint: { x: 48, y: 48 },
    },
    {
      id: "marketing-intelligence",
      title: "Marketing Intelligence",
      valueProposition: "Connect measurement and customer intelligence to more relevant, responsible commercial action.",
      problem: "Marketing and relationship teams need to understand incremental contribution and customer context before allocating spend or making an offer.",
      cogniriseRole: "Cognirise connects decision workflows, customer and campaign data, measurement practices and governed activation; Ekimetrics can contribute specialist measurement and customer-intelligence capability.",
      requiredInputs: ["Commercial objective and decision cadence", "Customer, campaign and consent data", "Measurement baseline, channel owners and offer guardrails"],
      firstDeliverable: "A measurement and activation design for one priority segment or decision, with retention and incremental-contribution measures.",
      measures: ["Incremental contribution rather than unqualified ROI", "Retention and offer suitability", "Reach, acquisition cost and customer response"],
      decisionBoundary: "Recommendations do not override consent, eligibility, product governance or fair-treatment requirements; accountable commercial and control owners approve activation.",
      action: { label: "Frame a growth decision", href: "/value-scan" },
      image: bankingMedia.marketingIntelligence,
      focalPoint: { x: 50, y: 50 },
    },
  ],
  voiceBanking: {
    platform: {
      name: "Lupitor",
      contribution: "Lupitor describes a platform for customer conversations with source checks, permission-bounded actions, deployment options and exported call, tool-call and verification records.",
      href: "https://www.lupitor.com/industries/banking",
      qualification: "Vendor description, not independent assurance, a compliance guarantee or a Cognirise deployment claim. Configuration, integration and the whole data path determine the applicable controls.",
    },
    cogniriseContribution: "Cognirise designs the banking journey and operating model around the platform: source grounding, identity and consent, integration, permitted actions and limits, human escalation, evaluation, monitoring and accountable ownership.",
    journeys: [
      { id: "accounts-cards", title: "Accounts & cards", scope: "Balance and transaction queries, card limits and statements, delivery and activation.", measures: ["Resolution rate", "Handling time", "Repeat contact"], controlBoundary: "Disclose and act only after the required identity checks; account changes and card actions follow configured product permissions." },
      { id: "payments-transfers", title: "Payments & transfers", scope: "Transfer status, failed or duplicate payments, standing orders and bill payments.", measures: ["Straight-through rate", "Manual fixes", "Resolution quality"], controlBoundary: "A response is not authority to move money. Identity verification, explicit transaction authorisation, limits, confirmation and human escalation remain visible." },
      { id: "loans-deposits", title: "Loans & deposits", scope: "Rate, instalment and limit questions, early-repayment figures, deposit maturity and renewal.", measures: ["Conversion", "Cross-sell", "Escalation quality"], controlBoundary: "Provide permitted information and route advice, exceptions, affordability or consequential decisions to authorised people." },
      { id: "fraud-card-security", title: "Fraud & card security", scope: "Lost or stolen card blocking, disputed-transaction reporting and suspicious-activity capture.", measures: ["Time to block", "Containment", "Case quality"], controlBoundary: "Urgent protective actions require verified identity, configured authority and a traceable hand-off; investigation and liability decisions remain accountable human work." },
      { id: "digital-channel-support", title: "Digital channel support", scope: "Login, password and SMS unblocking, mobile and internet-banking issues, limit-change and authorisation support.", measures: ["Self-service rate", "Calls to branch", "Resolution quality"], controlBoundary: "Credential recovery, device changes and limits use step-up verification, action controls and escalation paths defined by the bank." },
      { id: "collections-reminders", title: "Collections & reminders", scope: "Pre-due reminders, arrears outreach, promise-to-pay capture and restructuring hand-off.", measures: ["Recovery rate", "Cost to collect", "Vulnerable-customer escalation"], controlBoundary: "Approved wording, affordability and hardship signals take precedence over automation; the journey escalates to a person with the context retained." },
      { id: "campaigns-outbound", title: "Campaigns & outbound", scope: "Limit-increase and product offers, campaign calls and scheduled follow-up.", measures: ["Campaign reach", "Cost per acquisition", "Customer response and opt-out handling"], controlBoundary: "Consent, eligibility, contact preference, suitable treatment and offer approval constrain every outbound action." },
    ],
  },
  productionReadiness: {
    eyebrow: "Production readiness",
    heading: "From permission to action.",
    body: "A banking workflow earns production authority by moving through explicit permissions, validation and human checkpoints. The aim is not a more elaborate demo; it is a service that can be operated, challenged, recovered and improved.",
    practices: ["Ground responses in approved, current sources", "Use role-based access and minimum necessary data", "Define permitted actions, limits, approval gates and fallbacks", "Evaluate before and after change, then monitor quality, exceptions and drift", "Retain decision evidence and an auditable operating trail"],
    image: bankingMedia.productionReadiness,
    focalPoint: { x: 49, y: 52 },
    annotation: "Conceptual brand artwork. It represents controlled movement through permissions and checkpoints; it does not depict a client system or deployed technology.",
  },
  deliveryPath: {
    stages: [
      { stage: "Value discovery", owner: "Executive sponsor and business owner", outcome: "A named outcome, priority workflow, baseline and customer/control constraints." },
      { stage: "Workflow and data design", owner: "Process owner with data, technology and control partners", outcome: "A mapped path from source to action, including exceptions, permissions and integration responsibilities." },
      { stage: "Bounded pilot evaluation", owner: "Delivery owner with risk/control owner", outcome: "Evidence that the scoped workflow meets defined quality, safety, service and operating measures." },
      { stage: "Operational scale", owner: "Accountable operating owner", outcome: "Monitored production authority, incident and change management, and a decision to extend only where results warrant it." },
    ],
    practices: ["Measure a baseline before change", "Test representative and exception paths before release", "Monitor outcomes, fallbacks and control performance in operation", "Review scope and permissions when the workflow or its evidence changes"],
  },
  partners: [
    {
      name: "Lupitor",
      contribution: "A potential voice-platform contribution to permission-bounded customer conversations, verification flows and auditable records.",
      qualification: "Vendor capability description. Cognirise does not represent its vendor claims as independent assurance, bank-wide accuracy, compliance approval or a Cognirise result.",
      href: "https://www.lupitor.com/industries/banking",
    },
    {
      name: "Ekimetrics",
      contribution: "A potential specialist contribution to financial-services data architecture, algorithms, personalised relationships and measurement/customer intelligence.",
      qualification: "Vendor positioning, not an assertion of a new alliance, an exact ROI outcome or a Cognirise result.",
      href: "https://www.ekimetrics.com/en-us/industries/financial-services",
    },
  ],
  cta: {
    heading: "Choose the first workflow worth proving.",
    body: "Bring the workflow, owners, source systems, exception paths and the outcome you need to improve. In a Value Scan, we will help frame a bounded opportunity, its control boundary, the evidence needed for a pilot and a balanced scorecard for deciding what earns scale.",
    label: "Start a Value Scan",
    href: "/value-scan",
  },
  caseMembershipSnapshot: [
    { slug: "making-market-information-searchable", title: "Making market information searchable", order: 4, digest: "465a06bc9c55630694c7e45f79887e1bf7eeb87a1f8e82f97fdc37a31cdb0e4c" },
    { slug: "automating-recurring-tax-preparation", title: "Automating recurring tax preparation", order: 5, digest: "97f70aabeda60cebbca7cde9cb0162049ba051d6fa5c7d3be3fbd65dbd2838a4" },
    { slug: "governing-a-single-fee-schedule", title: "Governing a single fee schedule", order: 7, digest: "676cf59b27262b1c3fb87b952d84f345edefecb7510a9c106a056db482314f80" },
    { slug: "accelerating-governed-vehicle-offers", title: "Accelerating governed vehicle offers", order: 9, digest: "0a5d97363fb10cfd762865602ed7abbb899948925bf8e02ed25414f35115b6d1" },
    { slug: "answering-general-investment-questions", title: "Answering general investment questions", order: 10, digest: "bd6c3695139fce66cd66ef203cdce03a2b504b56f63d00b54b77dbdf06604410" },
    { slug: "checking-calls-through-risk-gates", title: "Checking calls through risk gates", order: 13, digest: "e776c962a2ef91439a5e036d568cc59e311577c8740bd3061aa90cb82b9143c0" },
    { slug: "monitoring-portfolio-early-warning-signals", title: "Monitoring portfolio early-warning signals", order: 18, digest: "fe4acec219c47c60cb2a5c679406c6b4313f2c55b9be6c5408a628626f51a029" },
    { slug: "tracing-provision-movements-earlier", title: "Tracing provision movements earlier", order: 20, digest: "47e0f5703105aea82eb48cc1488db7bf7ae5845e017e6924f2fc7035f436b406" },
  ],
};